{-# LANGUAGE CPP, ScopedTypeVariables, PatternSynonyms #-}

module Graphics.GL.Core33 where

import Control.Monad.IO.Class
import Foreign.Ptr
import Graphics.GL.Types
import System.IO.Unsafe

import Data.IORef
import Foreign.Storable

pattern GL_2D = 0x0600

pattern GL_2_BYTES = 0x1407

pattern GL_3D = 0x0601

pattern GL_3D_COLOR = 0x0602

pattern GL_3D_COLOR_TEXTURE = 0x0603

pattern GL_3_BYTES = 0x1408

pattern GL_4D_COLOR_TEXTURE = 0x0604

pattern GL_4_BYTES = 0x1409

pattern GL_ACCUM = 0x0100

pattern GL_ACCUM_ALPHA_BITS = 0x0D5B

pattern GL_ACCUM_BLUE_BITS = 0x0D5A

pattern GL_ACCUM_BUFFER_BIT = 0x00000200

pattern GL_ACCUM_CLEAR_VALUE = 0x0B80

pattern GL_ACCUM_GREEN_BITS = 0x0D59

pattern GL_ACCUM_RED_BITS = 0x0D58

pattern GL_ADD = 0x0104

pattern GL_ADD_SIGNED = 0x8574

pattern GL_ALIASED_POINT_SIZE_RANGE = 0x846D

pattern GL_ALL_ATTRIB_BITS = 0xFFFFFFFF

pattern GL_ALPHA12 = 0x803D

pattern GL_ALPHA16 = 0x803E

pattern GL_ALPHA4 = 0x803B

pattern GL_ALPHA8 = 0x803C

pattern GL_ALPHA_BIAS = 0x0D1D

pattern GL_ALPHA_BITS = 0x0D55

pattern GL_ALPHA_INTEGER = 0x8D97

pattern GL_ALPHA_SCALE = 0x0D1C

pattern GL_ALPHA_TEST = 0x0BC0

pattern GL_ALPHA_TEST_FUNC = 0x0BC1

pattern GL_ALPHA_TEST_REF = 0x0BC2

pattern GL_AMBIENT = 0x1200

pattern GL_AMBIENT_AND_DIFFUSE = 0x1602

pattern GL_ATTRIB_STACK_DEPTH = 0x0BB0

pattern GL_AUTO_NORMAL = 0x0D80

pattern GL_AUX0 = 0x0409

pattern GL_AUX1 = 0x040A

pattern GL_AUX2 = 0x040B

pattern GL_AUX3 = 0x040C

pattern GL_AUX_BUFFERS = 0x0C00

pattern GL_BITMAP = 0x1A00

pattern GL_BITMAP_TOKEN = 0x0704

pattern GL_BLUE_BIAS = 0x0D1B

pattern GL_BLUE_BITS = 0x0D54

pattern GL_BLUE_SCALE = 0x0D1A

pattern GL_C3F_V3F = 0x2A24

pattern GL_C4F_N3F_V3F = 0x2A26

pattern GL_C4UB_V2F = 0x2A22

pattern GL_C4UB_V3F = 0x2A23

pattern GL_CLAMP = 0x2900

pattern GL_CLAMP_FRAGMENT_COLOR = 0x891B

pattern GL_CLAMP_VERTEX_COLOR = 0x891A

pattern GL_CLIENT_ACTIVE_TEXTURE = 0x84E1

pattern GL_CLIENT_ALL_ATTRIB_BITS = 0xFFFFFFFF

pattern GL_CLIENT_ATTRIB_STACK_DEPTH = 0x0BB1

pattern GL_CLIENT_PIXEL_STORE_BIT = 0x00000001

pattern GL_CLIENT_VERTEX_ARRAY_BIT = 0x00000002

pattern GL_CLIP_PLANE0 = 0x3000

pattern GL_CLIP_PLANE1 = 0x3001

pattern GL_CLIP_PLANE2 = 0x3002

pattern GL_CLIP_PLANE3 = 0x3003

pattern GL_CLIP_PLANE4 = 0x3004

pattern GL_CLIP_PLANE5 = 0x3005

pattern GL_COEFF = 0x0A00

pattern GL_COLOR_ARRAY = 0x8076

pattern GL_COLOR_ARRAY_BUFFER_BINDING = 0x8898

pattern GL_COLOR_ARRAY_POINTER = 0x8090

pattern GL_COLOR_ARRAY_SIZE = 0x8081

pattern GL_COLOR_ARRAY_STRIDE = 0x8083

pattern GL_COLOR_ARRAY_TYPE = 0x8082

pattern GL_COLOR_INDEX = 0x1900

pattern GL_COLOR_INDEXES = 0x1603

pattern GL_COLOR_MATERIAL = 0x0B57

pattern GL_COLOR_MATERIAL_FACE = 0x0B55

pattern GL_COLOR_MATERIAL_PARAMETER = 0x0B56

pattern GL_COLOR_SUM = 0x8458

pattern GL_COMBINE = 0x8570

pattern GL_COMBINE_ALPHA = 0x8572

pattern GL_COMBINE_RGB = 0x8571

pattern GL_COMPARE_R_TO_TEXTURE = 0x884E

pattern GL_COMPILE = 0x1300

pattern GL_COMPILE_AND_EXECUTE = 0x1301

pattern GL_COMPRESSED_ALPHA = 0x84E9

pattern GL_COMPRESSED_INTENSITY = 0x84EC

pattern GL_COMPRESSED_LUMINANCE = 0x84EA

pattern GL_COMPRESSED_LUMINANCE_ALPHA = 0x84EB

pattern GL_COMPRESSED_SLUMINANCE = 0x8C4A

pattern GL_COMPRESSED_SLUMINANCE_ALPHA = 0x8C4B

pattern GL_CONSTANT = 0x8576

pattern GL_CONSTANT_ATTENUATION = 0x1207

pattern GL_COORD_REPLACE = 0x8862

pattern GL_COPY_PIXEL_TOKEN = 0x0706

pattern GL_CURRENT_BIT = 0x00000001

pattern GL_CURRENT_COLOR = 0x0B00

pattern GL_CURRENT_FOG_COORD = 0x8453

pattern GL_CURRENT_FOG_COORDINATE = 0x8453

pattern GL_CURRENT_INDEX = 0x0B01

pattern GL_CURRENT_NORMAL = 0x0B02

pattern GL_CURRENT_RASTER_COLOR = 0x0B04

pattern GL_CURRENT_RASTER_DISTANCE = 0x0B09

pattern GL_CURRENT_RASTER_INDEX = 0x0B05

pattern GL_CURRENT_RASTER_POSITION = 0x0B07

pattern GL_CURRENT_RASTER_POSITION_VALID = 0x0B08

pattern GL_CURRENT_RASTER_SECONDARY_COLOR = 0x845F

pattern GL_CURRENT_RASTER_TEXTURE_COORDS = 0x0B06

pattern GL_CURRENT_SECONDARY_COLOR = 0x8459

pattern GL_CURRENT_TEXTURE_COORDS = 0x0B03

pattern GL_DECAL = 0x2101

pattern GL_DEPTH_BIAS = 0x0D1F

pattern GL_DEPTH_BITS = 0x0D56

pattern GL_DEPTH_SCALE = 0x0D1E

pattern GL_DEPTH_TEXTURE_MODE = 0x884B

pattern GL_DIFFUSE = 0x1201

pattern GL_DOMAIN = 0x0A02

pattern GL_DOT3_RGB = 0x86AE

pattern GL_DOT3_RGBA = 0x86AF

pattern GL_DRAW_PIXEL_TOKEN = 0x0705

pattern GL_EDGE_FLAG = 0x0B43

pattern GL_EDGE_FLAG_ARRAY = 0x8079

pattern GL_EDGE_FLAG_ARRAY_BUFFER_BINDING = 0x889B

pattern GL_EDGE_FLAG_ARRAY_POINTER = 0x8093

pattern GL_EDGE_FLAG_ARRAY_STRIDE = 0x808C

pattern GL_EMISSION = 0x1600

pattern GL_ENABLE_BIT = 0x00002000

pattern GL_EVAL_BIT = 0x00010000

pattern GL_EXP = 0x0800

pattern GL_EXP2 = 0x0801

pattern GL_EYE_LINEAR = 0x2400

pattern GL_EYE_PLANE = 0x2502

pattern GL_FEEDBACK = 0x1C01

pattern GL_FEEDBACK_BUFFER_POINTER = 0x0DF0

pattern GL_FEEDBACK_BUFFER_SIZE = 0x0DF1

pattern GL_FEEDBACK_BUFFER_TYPE = 0x0DF2

pattern GL_FLAT = 0x1D00

pattern GL_FOG = 0x0B60

pattern GL_FOG_BIT = 0x00000080

pattern GL_FOG_COLOR = 0x0B66

pattern GL_FOG_COORD = 0x8451

pattern GL_FOG_COORDINATE = 0x8451

pattern GL_FOG_COORDINATE_ARRAY = 0x8457

pattern GL_FOG_COORDINATE_ARRAY_BUFFER_BINDING = 0x889D

pattern GL_FOG_COORDINATE_ARRAY_POINTER = 0x8456

pattern GL_FOG_COORDINATE_ARRAY_STRIDE = 0x8455

pattern GL_FOG_COORDINATE_ARRAY_TYPE = 0x8454

pattern GL_FOG_COORDINATE_SOURCE = 0x8450

pattern GL_FOG_COORD_ARRAY = 0x8457

pattern GL_FOG_COORD_ARRAY_BUFFER_BINDING = 0x889D

pattern GL_FOG_COORD_ARRAY_POINTER = 0x8456

pattern GL_FOG_COORD_ARRAY_STRIDE = 0x8455

pattern GL_FOG_COORD_ARRAY_TYPE = 0x8454

pattern GL_FOG_COORD_SRC = 0x8450

pattern GL_FOG_DENSITY = 0x0B62

pattern GL_FOG_END = 0x0B64

pattern GL_FOG_HINT = 0x0C54

pattern GL_FOG_INDEX = 0x0B61

pattern GL_FOG_MODE = 0x0B65

pattern GL_FOG_START = 0x0B63

pattern GL_FRAGMENT_DEPTH = 0x8452

pattern GL_GENERATE_MIPMAP = 0x8191

pattern GL_GENERATE_MIPMAP_HINT = 0x8192

pattern GL_GREEN_BIAS = 0x0D19

pattern GL_GREEN_BITS = 0x0D53

pattern GL_GREEN_SCALE = 0x0D18

pattern GL_HINT_BIT = 0x00008000

pattern GL_INDEX_ARRAY = 0x8077

pattern GL_INDEX_ARRAY_BUFFER_BINDING = 0x8899

pattern GL_INDEX_ARRAY_POINTER = 0x8091

pattern GL_INDEX_ARRAY_STRIDE = 0x8086

pattern GL_INDEX_ARRAY_TYPE = 0x8085

pattern GL_INDEX_BITS = 0x0D51

pattern GL_INDEX_CLEAR_VALUE = 0x0C20

pattern GL_INDEX_LOGIC_OP = 0x0BF1

pattern GL_INDEX_MODE = 0x0C30

pattern GL_INDEX_OFFSET = 0x0D13

pattern GL_INDEX_SHIFT = 0x0D12

pattern GL_INDEX_WRITEMASK = 0x0C21

pattern GL_INTENSITY = 0x8049

pattern GL_INTENSITY12 = 0x804C

pattern GL_INTENSITY16 = 0x804D

pattern GL_INTENSITY4 = 0x804A

pattern GL_INTENSITY8 = 0x804B

pattern GL_INTERPOLATE = 0x8575

pattern GL_LIGHT0 = 0x4000

pattern GL_LIGHT1 = 0x4001

pattern GL_LIGHT2 = 0x4002

pattern GL_LIGHT3 = 0x4003

pattern GL_LIGHT4 = 0x4004

pattern GL_LIGHT5 = 0x4005

pattern GL_LIGHT6 = 0x4006

pattern GL_LIGHT7 = 0x4007

pattern GL_LIGHTING = 0x0B50

pattern GL_LIGHTING_BIT = 0x00000040

pattern GL_LIGHT_MODEL_AMBIENT = 0x0B53

pattern GL_LIGHT_MODEL_COLOR_CONTROL = 0x81F8

pattern GL_LIGHT_MODEL_LOCAL_VIEWER = 0x0B51

pattern GL_LIGHT_MODEL_TWO_SIDE = 0x0B52

pattern GL_LINEAR_ATTENUATION = 0x1208

pattern GL_LINE_BIT = 0x00000004

pattern GL_LINE_RESET_TOKEN = 0x0707

pattern GL_LINE_STIPPLE = 0x0B24

pattern GL_LINE_STIPPLE_PATTERN = 0x0B25

pattern GL_LINE_STIPPLE_REPEAT = 0x0B26

pattern GL_LINE_TOKEN = 0x0702

pattern GL_LIST_BASE = 0x0B32

pattern GL_LIST_BIT = 0x00020000

pattern GL_LIST_INDEX = 0x0B33

pattern GL_LIST_MODE = 0x0B30

pattern GL_LOAD = 0x0101

pattern GL_LOGIC_OP = 0x0BF1

pattern GL_LUMINANCE = 0x1909

pattern GL_LUMINANCE12 = 0x8041

pattern GL_LUMINANCE12_ALPHA12 = 0x8047

pattern GL_LUMINANCE12_ALPHA4 = 0x8046

pattern GL_LUMINANCE16 = 0x8042

pattern GL_LUMINANCE16_ALPHA16 = 0x8048

pattern GL_LUMINANCE4 = 0x803F

pattern GL_LUMINANCE4_ALPHA4 = 0x8043

pattern GL_LUMINANCE6_ALPHA2 = 0x8044

pattern GL_LUMINANCE8 = 0x8040

pattern GL_LUMINANCE8_ALPHA8 = 0x8045

pattern GL_LUMINANCE_ALPHA = 0x190A

pattern GL_MAP1_COLOR_4 = 0x0D90

pattern GL_MAP1_GRID_DOMAIN = 0x0DD0

pattern GL_MAP1_GRID_SEGMENTS = 0x0DD1

pattern GL_MAP1_INDEX = 0x0D91

pattern GL_MAP1_NORMAL = 0x0D92

pattern GL_MAP1_TEXTURE_COORD_1 = 0x0D93

pattern GL_MAP1_TEXTURE_COORD_2 = 0x0D94

pattern GL_MAP1_TEXTURE_COORD_3 = 0x0D95

pattern GL_MAP1_TEXTURE_COORD_4 = 0x0D96

pattern GL_MAP1_VERTEX_3 = 0x0D97

pattern GL_MAP1_VERTEX_4 = 0x0D98

pattern GL_MAP2_COLOR_4 = 0x0DB0

pattern GL_MAP2_GRID_DOMAIN = 0x0DD2

pattern GL_MAP2_GRID_SEGMENTS = 0x0DD3

pattern GL_MAP2_INDEX = 0x0DB1

pattern GL_MAP2_NORMAL = 0x0DB2

pattern GL_MAP2_TEXTURE_COORD_1 = 0x0DB3

pattern GL_MAP2_TEXTURE_COORD_2 = 0x0DB4

pattern GL_MAP2_TEXTURE_COORD_3 = 0x0DB5

pattern GL_MAP2_TEXTURE_COORD_4 = 0x0DB6

pattern GL_MAP2_VERTEX_3 = 0x0DB7

pattern GL_MAP2_VERTEX_4 = 0x0DB8

pattern GL_MAP_COLOR = 0x0D10

pattern GL_MAP_STENCIL = 0x0D11

pattern GL_MATRIX_MODE = 0x0BA0

pattern GL_MAX_ATTRIB_STACK_DEPTH = 0x0D35

pattern GL_MAX_CLIENT_ATTRIB_STACK_DEPTH = 0x0D3B

pattern GL_MAX_CLIP_PLANES = 0x0D32

pattern GL_MAX_EVAL_ORDER = 0x0D30

pattern GL_MAX_LIGHTS = 0x0D31

pattern GL_MAX_LIST_NESTING = 0x0B31

pattern GL_MAX_MODELVIEW_STACK_DEPTH = 0x0D36

pattern GL_MAX_NAME_STACK_DEPTH = 0x0D37

pattern GL_MAX_PIXEL_MAP_TABLE = 0x0D34

pattern GL_MAX_PROJECTION_STACK_DEPTH = 0x0D38

pattern GL_MAX_TEXTURE_COORDS = 0x8871

pattern GL_MAX_TEXTURE_STACK_DEPTH = 0x0D39

pattern GL_MAX_TEXTURE_UNITS = 0x84E2

pattern GL_MODELVIEW = 0x1700

pattern GL_MODELVIEW_MATRIX = 0x0BA6

pattern GL_MODELVIEW_STACK_DEPTH = 0x0BA3

pattern GL_MODULATE = 0x2100

pattern GL_MULT = 0x0103

pattern GL_MULTISAMPLE_BIT = 0x20000000

pattern GL_N3F_V3F = 0x2A25

pattern GL_NAME_STACK_DEPTH = 0x0D70

pattern GL_NORMALIZE = 0x0BA1

pattern GL_NORMAL_ARRAY = 0x8075

pattern GL_NORMAL_ARRAY_BUFFER_BINDING = 0x8897

pattern GL_NORMAL_ARRAY_POINTER = 0x808F

pattern GL_NORMAL_ARRAY_STRIDE = 0x807F

pattern GL_NORMAL_ARRAY_TYPE = 0x807E

pattern GL_NORMAL_MAP = 0x8511

pattern GL_OBJECT_LINEAR = 0x2401

pattern GL_OBJECT_PLANE = 0x2501

pattern GL_OPERAND0_ALPHA = 0x8598

pattern GL_OPERAND0_RGB = 0x8590

pattern GL_OPERAND1_ALPHA = 0x8599

pattern GL_OPERAND1_RGB = 0x8591

pattern GL_OPERAND2_ALPHA = 0x859A

pattern GL_OPERAND2_RGB = 0x8592

pattern GL_ORDER = 0x0A01

pattern GL_PASS_THROUGH_TOKEN = 0x0700

pattern GL_PERSPECTIVE_CORRECTION_HINT = 0x0C50

pattern GL_PIXEL_MAP_A_TO_A = 0x0C79

pattern GL_PIXEL_MAP_A_TO_A_SIZE = 0x0CB9

pattern GL_PIXEL_MAP_B_TO_B = 0x0C78

pattern GL_PIXEL_MAP_B_TO_B_SIZE = 0x0CB8

pattern GL_PIXEL_MAP_G_TO_G = 0x0C77

pattern GL_PIXEL_MAP_G_TO_G_SIZE = 0x0CB7

pattern GL_PIXEL_MAP_I_TO_A = 0x0C75

pattern GL_PIXEL_MAP_I_TO_A_SIZE = 0x0CB5

pattern GL_PIXEL_MAP_I_TO_B = 0x0C74

pattern GL_PIXEL_MAP_I_TO_B_SIZE = 0x0CB4

pattern GL_PIXEL_MAP_I_TO_G = 0x0C73

pattern GL_PIXEL_MAP_I_TO_G_SIZE = 0x0CB3

pattern GL_PIXEL_MAP_I_TO_I = 0x0C70

pattern GL_PIXEL_MAP_I_TO_I_SIZE = 0x0CB0

pattern GL_PIXEL_MAP_I_TO_R = 0x0C72

pattern GL_PIXEL_MAP_I_TO_R_SIZE = 0x0CB2

pattern GL_PIXEL_MAP_R_TO_R = 0x0C76

pattern GL_PIXEL_MAP_R_TO_R_SIZE = 0x0CB6

pattern GL_PIXEL_MAP_S_TO_S = 0x0C71

pattern GL_PIXEL_MAP_S_TO_S_SIZE = 0x0CB1

pattern GL_PIXEL_MODE_BIT = 0x00000020

pattern GL_POINT_BIT = 0x00000002

pattern GL_POINT_DISTANCE_ATTENUATION = 0x8129

pattern GL_POINT_SIZE_MAX = 0x8127

pattern GL_POINT_SIZE_MIN = 0x8126

pattern GL_POINT_SMOOTH = 0x0B10

pattern GL_POINT_SMOOTH_HINT = 0x0C51

pattern GL_POINT_SPRITE = 0x8861

pattern GL_POINT_TOKEN = 0x0701

pattern GL_POLYGON = 0x0009

pattern GL_POLYGON_BIT = 0x00000008

pattern GL_POLYGON_STIPPLE = 0x0B42

pattern GL_POLYGON_STIPPLE_BIT = 0x00000010

pattern GL_POLYGON_TOKEN = 0x0703

pattern GL_POSITION = 0x1203

pattern GL_PREVIOUS = 0x8578

pattern GL_PRIMARY_COLOR = 0x8577

pattern GL_PROJECTION = 0x1701

pattern GL_PROJECTION_MATRIX = 0x0BA7

pattern GL_PROJECTION_STACK_DEPTH = 0x0BA4

pattern GL_Q = 0x2003

pattern GL_QUADRATIC_ATTENUATION = 0x1209

pattern GL_QUADS = 0x0007

pattern GL_QUAD_STRIP = 0x0008

pattern GL_R = 0x2002

pattern GL_RED_BIAS = 0x0D15

pattern GL_RED_BITS = 0x0D52

pattern GL_RED_SCALE = 0x0D14

pattern GL_REFLECTION_MAP = 0x8512

pattern GL_RENDER = 0x1C00

pattern GL_RENDER_MODE = 0x0C40

pattern GL_RESCALE_NORMAL = 0x803A

pattern GL_RETURN = 0x0102

pattern GL_RGBA_MODE = 0x0C31

pattern GL_RGB_SCALE = 0x8573

pattern GL_S = 0x2000

pattern GL_SCISSOR_BIT = 0x00080000

pattern GL_SECONDARY_COLOR_ARRAY = 0x845E

pattern GL_SECONDARY_COLOR_ARRAY_BUFFER_BINDING = 0x889C

pattern GL_SECONDARY_COLOR_ARRAY_POINTER = 0x845D

pattern GL_SECONDARY_COLOR_ARRAY_SIZE = 0x845A

pattern GL_SECONDARY_COLOR_ARRAY_STRIDE = 0x845C

pattern GL_SECONDARY_COLOR_ARRAY_TYPE = 0x845B

pattern GL_SELECT = 0x1C02

pattern GL_SELECTION_BUFFER_POINTER = 0x0DF3

pattern GL_SELECTION_BUFFER_SIZE = 0x0DF4

pattern GL_SEPARATE_SPECULAR_COLOR = 0x81FA

pattern GL_SHADE_MODEL = 0x0B54

pattern GL_SHININESS = 0x1601

pattern GL_SINGLE_COLOR = 0x81F9

pattern GL_SLUMINANCE = 0x8C46

pattern GL_SLUMINANCE8 = 0x8C47

pattern GL_SLUMINANCE8_ALPHA8 = 0x8C45

pattern GL_SLUMINANCE_ALPHA = 0x8C44

pattern GL_SMOOTH = 0x1D01

pattern GL_SOURCE0_ALPHA = 0x8588

pattern GL_SOURCE0_RGB = 0x8580

pattern GL_SOURCE1_ALPHA = 0x8589

pattern GL_SOURCE1_RGB = 0x8581

pattern GL_SOURCE2_ALPHA = 0x858A

pattern GL_SOURCE2_RGB = 0x8582

pattern GL_SPECULAR = 0x1202

pattern GL_SPHERE_MAP = 0x2402

pattern GL_SPOT_CUTOFF = 0x1206

pattern GL_SPOT_DIRECTION = 0x1204

pattern GL_SPOT_EXPONENT = 0x1205

pattern GL_SRC0_ALPHA = 0x8588

pattern GL_SRC0_RGB = 0x8580

pattern GL_SRC1_RGB = 0x8581

pattern GL_SRC2_ALPHA = 0x858A

pattern GL_SRC2_RGB = 0x8582

pattern GL_STACK_OVERFLOW = 0x0503

pattern GL_STACK_UNDERFLOW = 0x0504

pattern GL_STENCIL_BITS = 0x0D57

pattern GL_SUBTRACT = 0x84E7

pattern GL_T = 0x2001

pattern GL_T2F_C3F_V3F = 0x2A2A

pattern GL_T2F_C4F_N3F_V3F = 0x2A2C

pattern GL_T2F_C4UB_V3F = 0x2A29

pattern GL_T2F_N3F_V3F = 0x2A2B

pattern GL_T2F_V3F = 0x2A27

pattern GL_T4F_C4F_N3F_V4F = 0x2A2D

pattern GL_T4F_V4F = 0x2A28

pattern GL_TEXTURE_BIT = 0x00040000

pattern GL_TEXTURE_BORDER = 0x1005

pattern GL_TEXTURE_COMPONENTS = 0x1003

pattern GL_TEXTURE_COORD_ARRAY = 0x8078

pattern GL_TEXTURE_COORD_ARRAY_BUFFER_BINDING = 0x889A

pattern GL_TEXTURE_COORD_ARRAY_POINTER = 0x8092

pattern GL_TEXTURE_COORD_ARRAY_SIZE = 0x8088

pattern GL_TEXTURE_COORD_ARRAY_STRIDE = 0x808A

pattern GL_TEXTURE_COORD_ARRAY_TYPE = 0x8089

pattern GL_TEXTURE_ENV = 0x2300

pattern GL_TEXTURE_ENV_COLOR = 0x2201

pattern GL_TEXTURE_ENV_MODE = 0x2200

pattern GL_TEXTURE_FILTER_CONTROL = 0x8500

pattern GL_TEXTURE_GEN_MODE = 0x2500

pattern GL_TEXTURE_GEN_Q = 0x0C63

pattern GL_TEXTURE_GEN_R = 0x0C62

pattern GL_TEXTURE_GEN_S = 0x0C60

pattern GL_TEXTURE_GEN_T = 0x0C61

pattern GL_TEXTURE_INTENSITY_SIZE = 0x8061

pattern GL_TEXTURE_INTENSITY_TYPE = 0x8C15

pattern GL_TEXTURE_LUMINANCE_SIZE = 0x8060

pattern GL_TEXTURE_LUMINANCE_TYPE = 0x8C14

pattern GL_TEXTURE_MATRIX = 0x0BA8

pattern GL_TEXTURE_PRIORITY = 0x8066

pattern GL_TEXTURE_RESIDENT = 0x8067

pattern GL_TEXTURE_STACK_DEPTH = 0x0BA5

pattern GL_TRANSFORM_BIT = 0x00001000

pattern GL_TRANSPOSE_COLOR_MATRIX = 0x84E6

pattern GL_TRANSPOSE_MODELVIEW_MATRIX = 0x84E3

pattern GL_TRANSPOSE_PROJECTION_MATRIX = 0x84E4

pattern GL_TRANSPOSE_TEXTURE_MATRIX = 0x84E5

pattern GL_V2F = 0x2A20

pattern GL_V3F = 0x2A21

pattern GL_VERTEX_ARRAY = 0x8074

pattern GL_VERTEX_ARRAY_BUFFER_BINDING = 0x8896

pattern GL_VERTEX_ARRAY_POINTER = 0x808E

pattern GL_VERTEX_ARRAY_SIZE = 0x807A

pattern GL_VERTEX_ARRAY_STRIDE = 0x807C

pattern GL_VERTEX_ARRAY_TYPE = 0x807B

pattern GL_VERTEX_PROGRAM_TWO_SIDE = 0x8643

pattern GL_VIEWPORT_BIT = 0x00000800

pattern GL_WEIGHT_ARRAY_BUFFER_BINDING = 0x889E

pattern GL_ZOOM_X = 0x0D16

pattern GL_ZOOM_Y = 0x0D17

pattern GL_ACTIVE_ATTRIBUTES = 0x8B89

pattern GL_ACTIVE_ATTRIBUTE_MAX_LENGTH = 0x8B8A

pattern GL_ACTIVE_TEXTURE = 0x84E0

pattern GL_ACTIVE_UNIFORMS = 0x8B86

pattern GL_ACTIVE_UNIFORM_BLOCKS = 0x8A36

pattern GL_ACTIVE_UNIFORM_BLOCK_MAX_NAME_LENGTH = 0x8A35

pattern GL_ACTIVE_UNIFORM_MAX_LENGTH = 0x8B87

pattern GL_ALIASED_LINE_WIDTH_RANGE = 0x846E

pattern GL_ALPHA = 0x1906

pattern GL_ALREADY_SIGNALED = 0x911A

pattern GL_ALWAYS = 0x0207

pattern GL_AND = 0x1501

pattern GL_AND_INVERTED = 0x1504

pattern GL_AND_REVERSE = 0x1502

pattern GL_ARRAY_BUFFER = 0x8892

pattern GL_ARRAY_BUFFER_BINDING = 0x8894

pattern GL_ATTACHED_SHADERS = 0x8B85

pattern GL_BACK = 0x0405

pattern GL_BACK_LEFT = 0x0402

pattern GL_BACK_RIGHT = 0x0403

pattern GL_BGR = 0x80E0

pattern GL_BGRA = 0x80E1

pattern GL_BGRA_INTEGER = 0x8D9B

pattern GL_BGR_INTEGER = 0x8D9A

pattern GL_BLEND = 0x0BE2

pattern GL_BLEND_COLOR = 0x8005

pattern GL_BLEND_DST = 0x0BE0

pattern GL_BLEND_DST_ALPHA = 0x80CA

pattern GL_BLEND_DST_RGB = 0x80C8

pattern GL_BLEND_EQUATION_ALPHA = 0x883D

pattern GL_BLEND_EQUATION_RGB = 0x8009

pattern GL_BLEND_SRC = 0x0BE1

pattern GL_BLEND_SRC_ALPHA = 0x80CB

pattern GL_BLEND_SRC_RGB = 0x80C9

pattern GL_BLUE = 0x1905

pattern GL_BLUE_INTEGER = 0x8D96

pattern GL_BOOL = 0x8B56

pattern GL_BOOL_VEC2 = 0x8B57

pattern GL_BOOL_VEC3 = 0x8B58

pattern GL_BOOL_VEC4 = 0x8B59

pattern GL_BUFFER_ACCESS = 0x88BB

pattern GL_BUFFER_ACCESS_FLAGS = 0x911F

pattern GL_BUFFER_MAPPED = 0x88BC

pattern GL_BUFFER_MAP_LENGTH = 0x9120

pattern GL_BUFFER_MAP_OFFSET = 0x9121

pattern GL_BUFFER_MAP_POINTER = 0x88BD

pattern GL_BUFFER_SIZE = 0x8764

pattern GL_BUFFER_USAGE = 0x8765

pattern GL_BYTE = 0x1400

pattern GL_CCW = 0x0901

pattern GL_CLAMP_READ_COLOR = 0x891C

pattern GL_CLAMP_TO_BORDER = 0x812D

pattern GL_CLAMP_TO_EDGE = 0x812F

pattern GL_CLEAR = 0x1500

pattern GL_CLIP_DISTANCE0 = 0x3000

pattern GL_CLIP_DISTANCE1 = 0x3001

pattern GL_CLIP_DISTANCE2 = 0x3002

pattern GL_CLIP_DISTANCE3 = 0x3003

pattern GL_CLIP_DISTANCE4 = 0x3004

pattern GL_CLIP_DISTANCE5 = 0x3005

pattern GL_CLIP_DISTANCE6 = 0x3006

pattern GL_CLIP_DISTANCE7 = 0x3007

pattern GL_COLOR = 0x1800

pattern GL_COLOR_ATTACHMENT0 = 0x8CE0

pattern GL_COLOR_ATTACHMENT1 = 0x8CE1

pattern GL_COLOR_ATTACHMENT10 = 0x8CEA

pattern GL_COLOR_ATTACHMENT11 = 0x8CEB

pattern GL_COLOR_ATTACHMENT12 = 0x8CEC

pattern GL_COLOR_ATTACHMENT13 = 0x8CED

pattern GL_COLOR_ATTACHMENT14 = 0x8CEE

pattern GL_COLOR_ATTACHMENT15 = 0x8CEF

pattern GL_COLOR_ATTACHMENT16 = 0x8CF0

pattern GL_COLOR_ATTACHMENT17 = 0x8CF1

pattern GL_COLOR_ATTACHMENT18 = 0x8CF2

pattern GL_COLOR_ATTACHMENT19 = 0x8CF3

pattern GL_COLOR_ATTACHMENT2 = 0x8CE2

pattern GL_COLOR_ATTACHMENT20 = 0x8CF4

pattern GL_COLOR_ATTACHMENT21 = 0x8CF5

pattern GL_COLOR_ATTACHMENT22 = 0x8CF6

pattern GL_COLOR_ATTACHMENT23 = 0x8CF7

pattern GL_COLOR_ATTACHMENT24 = 0x8CF8

pattern GL_COLOR_ATTACHMENT25 = 0x8CF9

pattern GL_COLOR_ATTACHMENT26 = 0x8CFA

pattern GL_COLOR_ATTACHMENT27 = 0x8CFB

pattern GL_COLOR_ATTACHMENT28 = 0x8CFC

pattern GL_COLOR_ATTACHMENT29 = 0x8CFD

pattern GL_COLOR_ATTACHMENT3 = 0x8CE3

pattern GL_COLOR_ATTACHMENT30 = 0x8CFE

pattern GL_COLOR_ATTACHMENT31 = 0x8CFF

pattern GL_COLOR_ATTACHMENT4 = 0x8CE4

pattern GL_COLOR_ATTACHMENT5 = 0x8CE5

pattern GL_COLOR_ATTACHMENT6 = 0x8CE6

pattern GL_COLOR_ATTACHMENT7 = 0x8CE7

pattern GL_COLOR_ATTACHMENT8 = 0x8CE8

pattern GL_COLOR_ATTACHMENT9 = 0x8CE9

pattern GL_COLOR_BUFFER_BIT = 0x00004000

pattern GL_COLOR_CLEAR_VALUE = 0x0C22

pattern GL_COLOR_LOGIC_OP = 0x0BF2

pattern GL_COLOR_WRITEMASK = 0x0C23

pattern GL_COMPARE_REF_TO_TEXTURE = 0x884E

pattern GL_COMPILE_STATUS = 0x8B81

pattern GL_COMPRESSED_RED = 0x8225

pattern GL_COMPRESSED_RED_RGTC1 = 0x8DBB

pattern GL_COMPRESSED_RG = 0x8226

pattern GL_COMPRESSED_RGB = 0x84ED

pattern GL_COMPRESSED_RGBA = 0x84EE

pattern GL_COMPRESSED_RG_RGTC2 = 0x8DBD

pattern GL_COMPRESSED_SIGNED_RED_RGTC1 = 0x8DBC

pattern GL_COMPRESSED_SIGNED_RG_RGTC2 = 0x8DBE

pattern GL_COMPRESSED_SRGB = 0x8C48

pattern GL_COMPRESSED_SRGB_ALPHA = 0x8C49

pattern GL_COMPRESSED_TEXTURE_FORMATS = 0x86A3

pattern GL_CONDITION_SATISFIED = 0x911C

pattern GL_CONSTANT_ALPHA = 0x8003

pattern GL_CONSTANT_COLOR = 0x8001

pattern GL_CONTEXT_FLAGS = 0x821E

pattern GL_CONTEXT_FLAG_FORWARD_COMPATIBLE_BIT = 0x00000001

pattern GL_COPY = 0x1503

pattern GL_COPY_INVERTED = 0x150C

pattern GL_COPY_READ_BUFFER = 0x8F36

pattern GL_COPY_WRITE_BUFFER = 0x8F37

pattern GL_CULL_FACE = 0x0B44

pattern GL_CULL_FACE_MODE = 0x0B45

pattern GL_CURRENT_PROGRAM = 0x8B8D

pattern GL_CURRENT_QUERY = 0x8865

pattern GL_CURRENT_VERTEX_ATTRIB = 0x8626

pattern GL_CW = 0x0900

pattern GL_DECR = 0x1E03

pattern GL_DECR_WRAP = 0x8508

pattern GL_DELETE_STATUS = 0x8B80

pattern GL_DEPTH = 0x1801

pattern GL_DEPTH24_STENCIL8 = 0x88F0

pattern GL_DEPTH32F_STENCIL8 = 0x8CAD

pattern GL_DEPTH_ATTACHMENT = 0x8D00

pattern GL_DEPTH_BUFFER_BIT = 0x00000100

pattern GL_DEPTH_CLAMP = 0x864F

pattern GL_DEPTH_CLEAR_VALUE = 0x0B73

pattern GL_DEPTH_COMPONENT = 0x1902

pattern GL_DEPTH_COMPONENT16 = 0x81A5

pattern GL_DEPTH_COMPONENT24 = 0x81A6

pattern GL_DEPTH_COMPONENT32 = 0x81A7

pattern GL_DEPTH_COMPONENT32F = 0x8CAC

pattern GL_DEPTH_FUNC = 0x0B74

pattern GL_DEPTH_RANGE = 0x0B70

pattern GL_DEPTH_STENCIL = 0x84F9

pattern GL_DEPTH_STENCIL_ATTACHMENT = 0x821A

pattern GL_DEPTH_TEST = 0x0B71

pattern GL_DEPTH_WRITEMASK = 0x0B72

pattern GL_DITHER = 0x0BD0

pattern GL_DONT_CARE = 0x1100

pattern GL_DOUBLE = 0x140A

pattern GL_DOUBLEBUFFER = 0x0C32

pattern GL_DRAW_BUFFER = 0x0C01

pattern GL_DRAW_BUFFER0 = 0x8825

pattern GL_DRAW_BUFFER1 = 0x8826

pattern GL_DRAW_BUFFER10 = 0x882F

pattern GL_DRAW_BUFFER11 = 0x8830

pattern GL_DRAW_BUFFER12 = 0x8831

pattern GL_DRAW_BUFFER13 = 0x8832

pattern GL_DRAW_BUFFER14 = 0x8833

pattern GL_DRAW_BUFFER15 = 0x8834

pattern GL_DRAW_BUFFER2 = 0x8827

pattern GL_DRAW_BUFFER3 = 0x8828

pattern GL_DRAW_BUFFER4 = 0x8829

pattern GL_DRAW_BUFFER5 = 0x882A

pattern GL_DRAW_BUFFER6 = 0x882B

pattern GL_DRAW_BUFFER7 = 0x882C

pattern GL_DRAW_BUFFER8 = 0x882D

pattern GL_DRAW_BUFFER9 = 0x882E

pattern GL_DRAW_FRAMEBUFFER = 0x8CA9

pattern GL_DRAW_FRAMEBUFFER_BINDING = 0x8CA6

pattern GL_DST_ALPHA = 0x0304

pattern GL_DST_COLOR = 0x0306

pattern GL_DYNAMIC_COPY = 0x88EA

pattern GL_DYNAMIC_DRAW = 0x88E8

pattern GL_DYNAMIC_READ = 0x88E9

pattern GL_ELEMENT_ARRAY_BUFFER = 0x8893

pattern GL_ELEMENT_ARRAY_BUFFER_BINDING = 0x8895

pattern GL_EQUAL = 0x0202

pattern GL_EQUIV = 0x1509

pattern GL_EXTENSIONS = 0x1F03

pattern GL_FALSE = 0

pattern GL_FASTEST = 0x1101

pattern GL_FILL = 0x1B02

pattern GL_FIRST_VERTEX_CONVENTION = 0x8E4D

pattern GL_FIXED_ONLY = 0x891D

pattern GL_FLOAT = 0x1406

pattern GL_FLOAT_32_UNSIGNED_INT_24_8_REV = 0x8DAD

pattern GL_FLOAT_MAT2 = 0x8B5A

pattern GL_FLOAT_MAT2x3 = 0x8B65

pattern GL_FLOAT_MAT2x4 = 0x8B66

pattern GL_FLOAT_MAT3 = 0x8B5B

pattern GL_FLOAT_MAT3x2 = 0x8B67

pattern GL_FLOAT_MAT3x4 = 0x8B68

pattern GL_FLOAT_MAT4 = 0x8B5C

pattern GL_FLOAT_MAT4x2 = 0x8B69

pattern GL_FLOAT_MAT4x3 = 0x8B6A

pattern GL_FLOAT_VEC2 = 0x8B50

pattern GL_FLOAT_VEC3 = 0x8B51

pattern GL_FLOAT_VEC4 = 0x8B52

pattern GL_FRAGMENT_SHADER = 0x8B30

pattern GL_FRAGMENT_SHADER_DERIVATIVE_HINT = 0x8B8B

pattern GL_FRAMEBUFFER = 0x8D40

pattern GL_FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE = 0x8215

pattern GL_FRAMEBUFFER_ATTACHMENT_BLUE_SIZE = 0x8214

pattern GL_FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING = 0x8210

pattern GL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE = 0x8211

pattern GL_FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE = 0x8216

pattern GL_FRAMEBUFFER_ATTACHMENT_GREEN_SIZE = 0x8213

pattern GL_FRAMEBUFFER_ATTACHMENT_LAYERED = 0x8DA7

pattern GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME = 0x8CD1

pattern GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE = 0x8CD0

pattern GL_FRAMEBUFFER_ATTACHMENT_RED_SIZE = 0x8212

pattern GL_FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE = 0x8217

pattern GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE = 0x8CD3

pattern GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER = 0x8CD4

pattern GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL = 0x8CD2

pattern GL_FRAMEBUFFER_BINDING = 0x8CA6

pattern GL_FRAMEBUFFER_COMPLETE = 0x8CD5

pattern GL_FRAMEBUFFER_DEFAULT = 0x8218

pattern GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT = 0x8CD6

pattern GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER = 0x8CDB

pattern GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS = 0x8DA8

pattern GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT = 0x8CD7

pattern GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE = 0x8D56

pattern GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER = 0x8CDC

pattern GL_FRAMEBUFFER_SRGB = 0x8DB9

pattern GL_FRAMEBUFFER_UNDEFINED = 0x8219

pattern GL_FRAMEBUFFER_UNSUPPORTED = 0x8CDD

pattern GL_FRONT = 0x0404

pattern GL_FRONT_AND_BACK = 0x0408

pattern GL_FRONT_FACE = 0x0B46

pattern GL_FRONT_LEFT = 0x0400

pattern GL_FRONT_RIGHT = 0x0401

pattern GL_FUNC_ADD = 0x8006

pattern GL_FUNC_REVERSE_SUBTRACT = 0x800B

pattern GL_FUNC_SUBTRACT = 0x800A

pattern GL_GEOMETRY_INPUT_TYPE = 0x8917

pattern GL_GEOMETRY_OUTPUT_TYPE = 0x8918

pattern GL_GEOMETRY_SHADER = 0x8DD9

pattern GL_GEOMETRY_VERTICES_OUT = 0x8916

pattern GL_GEQUAL = 0x0206

pattern GL_GREATER = 0x0204

pattern GL_GREEN = 0x1904

pattern GL_GREEN_INTEGER = 0x8D95

pattern GL_HALF_FLOAT = 0x140B

pattern GL_INCR = 0x1E02

pattern GL_INCR_WRAP = 0x8507

pattern GL_INDEX = 0x8222

pattern GL_INFO_LOG_LENGTH = 0x8B84

pattern GL_INT = 0x1404

pattern GL_INTERLEAVED_ATTRIBS = 0x8C8C

pattern GL_INT_SAMPLER_1D = 0x8DC9

pattern GL_INT_SAMPLER_1D_ARRAY = 0x8DCE

pattern GL_INT_SAMPLER_2D = 0x8DCA

pattern GL_INT_SAMPLER_2D_ARRAY = 0x8DCF

pattern GL_INT_SAMPLER_2D_MULTISAMPLE = 0x9109

pattern GL_INT_SAMPLER_2D_MULTISAMPLE_ARRAY = 0x910C

pattern GL_INT_SAMPLER_2D_RECT = 0x8DCD

pattern GL_INT_SAMPLER_3D = 0x8DCB

pattern GL_INT_SAMPLER_BUFFER = 0x8DD0

pattern GL_INT_SAMPLER_CUBE = 0x8DCC

pattern GL_INT_VEC2 = 0x8B53

pattern GL_INT_VEC3 = 0x8B54

pattern GL_INT_VEC4 = 0x8B55

pattern GL_INVALID_ENUM = 0x0500

pattern GL_INVALID_FRAMEBUFFER_OPERATION = 0x0506

pattern GL_INVALID_INDEX = 0xFFFFFFFF

pattern GL_INVALID_OPERATION = 0x0502

pattern GL_INVALID_VALUE = 0x0501

pattern GL_INVERT = 0x150A

pattern GL_KEEP = 0x1E00

pattern GL_LAST_VERTEX_CONVENTION = 0x8E4E

pattern GL_LEFT = 0x0406

pattern GL_LEQUAL = 0x0203

pattern GL_LESS = 0x0201

pattern GL_LINE = 0x1B01

pattern GL_LINEAR = 0x2601

pattern GL_LINEAR_MIPMAP_LINEAR = 0x2703

pattern GL_LINEAR_MIPMAP_NEAREST = 0x2701

pattern GL_LINES = 0x0001

pattern GL_LINES_ADJACENCY = 0x000A

pattern GL_LINE_LOOP = 0x0002

pattern GL_LINE_SMOOTH = 0x0B20

pattern GL_LINE_SMOOTH_HINT = 0x0C52

pattern GL_LINE_STRIP = 0x0003

pattern GL_LINE_STRIP_ADJACENCY = 0x000B

pattern GL_LINE_WIDTH = 0x0B21

pattern GL_LINE_WIDTH_GRANULARITY = 0x0B23

pattern GL_LINE_WIDTH_RANGE = 0x0B22

pattern GL_LINK_STATUS = 0x8B82

pattern GL_LOGIC_OP_MODE = 0x0BF0

pattern GL_LOWER_LEFT = 0x8CA1

pattern GL_MAJOR_VERSION = 0x821B

pattern GL_MAP_FLUSH_EXPLICIT_BIT = 0x0010

pattern GL_MAP_INVALIDATE_BUFFER_BIT = 0x0008

pattern GL_MAP_INVALIDATE_RANGE_BIT = 0x0004

pattern GL_MAP_READ_BIT = 0x0001

pattern GL_MAP_UNSYNCHRONIZED_BIT = 0x0020

pattern GL_MAP_WRITE_BIT = 0x0002

pattern GL_MAX = 0x8008

pattern GL_MAX_3D_TEXTURE_SIZE = 0x8073

pattern GL_MAX_ARRAY_TEXTURE_LAYERS = 0x88FF

pattern GL_MAX_CLIP_DISTANCES = 0x0D32

pattern GL_MAX_COLOR_ATTACHMENTS = 0x8CDF

pattern GL_MAX_COLOR_TEXTURE_SAMPLES = 0x910E

pattern GL_MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS = 0x8A33

pattern GL_MAX_COMBINED_GEOMETRY_UNIFORM_COMPONENTS = 0x8A32

pattern GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS = 0x8B4D

pattern GL_MAX_COMBINED_UNIFORM_BLOCKS = 0x8A2E

pattern GL_MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS = 0x8A31

pattern GL_MAX_CUBE_MAP_TEXTURE_SIZE = 0x851C

pattern GL_MAX_DEPTH_TEXTURE_SAMPLES = 0x910F

pattern GL_MAX_DRAW_BUFFERS = 0x8824

pattern GL_MAX_ELEMENTS_INDICES = 0x80E9

pattern GL_MAX_ELEMENTS_VERTICES = 0x80E8

pattern GL_MAX_FRAGMENT_INPUT_COMPONENTS = 0x9125

pattern GL_MAX_FRAGMENT_UNIFORM_BLOCKS = 0x8A2D

pattern GL_MAX_FRAGMENT_UNIFORM_COMPONENTS = 0x8B49

pattern GL_MAX_GEOMETRY_INPUT_COMPONENTS = 0x9123

pattern GL_MAX_GEOMETRY_OUTPUT_COMPONENTS = 0x9124

pattern GL_MAX_GEOMETRY_OUTPUT_VERTICES = 0x8DE0

pattern GL_MAX_GEOMETRY_TEXTURE_IMAGE_UNITS = 0x8C29

pattern GL_MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS = 0x8DE1

pattern GL_MAX_GEOMETRY_UNIFORM_BLOCKS = 0x8A2C

pattern GL_MAX_GEOMETRY_UNIFORM_COMPONENTS = 0x8DDF

pattern GL_MAX_INTEGER_SAMPLES = 0x9110

pattern GL_MAX_PROGRAM_TEXEL_OFFSET = 0x8905

pattern GL_MAX_RECTANGLE_TEXTURE_SIZE = 0x84F8

pattern GL_MAX_RENDERBUFFER_SIZE = 0x84E8

pattern GL_MAX_SAMPLES = 0x8D57

pattern GL_MAX_SAMPLE_MASK_WORDS = 0x8E59

pattern GL_MAX_SERVER_WAIT_TIMEOUT = 0x9111

pattern GL_MAX_TEXTURE_BUFFER_SIZE = 0x8C2B

pattern GL_MAX_TEXTURE_IMAGE_UNITS = 0x8872

pattern GL_MAX_TEXTURE_LOD_BIAS = 0x84FD

pattern GL_MAX_TEXTURE_SIZE = 0x0D33

pattern GL_MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS = 0x8C8A

pattern GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS = 0x8C8B

pattern GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS = 0x8C80

pattern GL_MAX_UNIFORM_BLOCK_SIZE = 0x8A30

pattern GL_MAX_UNIFORM_BUFFER_BINDINGS = 0x8A2F

pattern GL_MAX_VARYING_COMPONENTS = 0x8B4B

pattern GL_MAX_VARYING_FLOATS = 0x8B4B

pattern GL_MAX_VERTEX_ATTRIBS = 0x8869

pattern GL_MAX_VERTEX_OUTPUT_COMPONENTS = 0x9122

pattern GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS = 0x8B4C

pattern GL_MAX_VERTEX_UNIFORM_BLOCKS = 0x8A2B

pattern GL_MAX_VERTEX_UNIFORM_COMPONENTS = 0x8B4A

pattern GL_MAX_VIEWPORT_DIMS = 0x0D3A

pattern GL_MIN = 0x8007

pattern GL_MINOR_VERSION = 0x821C

pattern GL_MIN_PROGRAM_TEXEL_OFFSET = 0x8904

pattern GL_MIRRORED_REPEAT = 0x8370

pattern GL_MULTISAMPLE = 0x809D

pattern GL_NAND = 0x150E

pattern GL_NEAREST = 0x2600

pattern GL_NEAREST_MIPMAP_LINEAR = 0x2702

pattern GL_NEAREST_MIPMAP_NEAREST = 0x2700

pattern GL_NEVER = 0x0200

pattern GL_NICEST = 0x1102

pattern GL_NONE = 0

pattern GL_NOOP = 0x1505

pattern GL_NOR = 0x1508

pattern GL_NOTEQUAL = 0x0205

pattern GL_NO_ERROR = 0

pattern GL_NUM_COMPRESSED_TEXTURE_FORMATS = 0x86A2

pattern GL_NUM_EXTENSIONS = 0x821D

pattern GL_OBJECT_TYPE = 0x9112

pattern GL_ONE = 1

pattern GL_ONE_MINUS_CONSTANT_ALPHA = 0x8004

pattern GL_ONE_MINUS_CONSTANT_COLOR = 0x8002

pattern GL_ONE_MINUS_DST_ALPHA = 0x0305

pattern GL_ONE_MINUS_DST_COLOR = 0x0307

pattern GL_ONE_MINUS_SRC_ALPHA = 0x0303

pattern GL_ONE_MINUS_SRC_COLOR = 0x0301

pattern GL_OR = 0x1507

pattern GL_OR_INVERTED = 0x150D

pattern GL_OR_REVERSE = 0x150B

pattern GL_OUT_OF_MEMORY = 0x0505

pattern GL_PACK_ALIGNMENT = 0x0D05

pattern GL_PACK_IMAGE_HEIGHT = 0x806C

pattern GL_PACK_LSB_FIRST = 0x0D01

pattern GL_PACK_ROW_LENGTH = 0x0D02

pattern GL_PACK_SKIP_IMAGES = 0x806B

pattern GL_PACK_SKIP_PIXELS = 0x0D04

pattern GL_PACK_SKIP_ROWS = 0x0D03

pattern GL_PACK_SWAP_BYTES = 0x0D00

pattern GL_PIXEL_PACK_BUFFER = 0x88EB

pattern GL_PIXEL_PACK_BUFFER_BINDING = 0x88ED

pattern GL_PIXEL_UNPACK_BUFFER = 0x88EC

pattern GL_PIXEL_UNPACK_BUFFER_BINDING = 0x88EF

pattern GL_POINT = 0x1B00

pattern GL_POINTS = 0x0000

pattern GL_POINT_FADE_THRESHOLD_SIZE = 0x8128

pattern GL_POINT_SIZE = 0x0B11

pattern GL_POINT_SIZE_GRANULARITY = 0x0B13

pattern GL_POINT_SIZE_RANGE = 0x0B12

pattern GL_POINT_SPRITE_COORD_ORIGIN = 0x8CA0

pattern GL_POLYGON_MODE = 0x0B40

pattern GL_POLYGON_OFFSET_FACTOR = 0x8038

pattern GL_POLYGON_OFFSET_FILL = 0x8037

pattern GL_POLYGON_OFFSET_LINE = 0x2A02

pattern GL_POLYGON_OFFSET_POINT = 0x2A01

pattern GL_POLYGON_OFFSET_UNITS = 0x2A00

pattern GL_POLYGON_SMOOTH = 0x0B41

pattern GL_POLYGON_SMOOTH_HINT = 0x0C53

pattern GL_PRIMITIVES_GENERATED = 0x8C87

pattern GL_PRIMITIVE_RESTART = 0x8F9D

pattern GL_PRIMITIVE_RESTART_INDEX = 0x8F9E

pattern GL_PROVOKING_VERTEX = 0x8E4F

pattern GL_PROXY_TEXTURE_1D = 0x8063

pattern GL_PROXY_TEXTURE_1D_ARRAY = 0x8C19

pattern GL_PROXY_TEXTURE_2D = 0x8064

pattern GL_PROXY_TEXTURE_2D_ARRAY = 0x8C1B

pattern GL_PROXY_TEXTURE_2D_MULTISAMPLE = 0x9101

pattern GL_PROXY_TEXTURE_2D_MULTISAMPLE_ARRAY = 0x9103

pattern GL_PROXY_TEXTURE_3D = 0x8070

pattern GL_PROXY_TEXTURE_CUBE_MAP = 0x851B

pattern GL_PROXY_TEXTURE_RECTANGLE = 0x84F7

pattern GL_QUADS_FOLLOW_PROVOKING_VERTEX_CONVENTION = 0x8E4C

pattern GL_QUERY_BY_REGION_NO_WAIT = 0x8E16

pattern GL_QUERY_BY_REGION_WAIT = 0x8E15

pattern GL_QUERY_COUNTER_BITS = 0x8864

pattern GL_QUERY_NO_WAIT = 0x8E14

pattern GL_QUERY_RESULT = 0x8866

pattern GL_QUERY_RESULT_AVAILABLE = 0x8867

pattern GL_QUERY_WAIT = 0x8E13

pattern GL_R11F_G11F_B10F = 0x8C3A

pattern GL_R16 = 0x822A

pattern GL_R16F = 0x822D

pattern GL_R16I = 0x8233

pattern GL_R16UI = 0x8234

pattern GL_R16_SNORM = 0x8F98

pattern GL_R32F = 0x822E

pattern GL_R32I = 0x8235

pattern GL_R32UI = 0x8236

pattern GL_R3_G3_B2 = 0x2A10

pattern GL_R8 = 0x8229

pattern GL_R8I = 0x8231

pattern GL_R8UI = 0x8232

pattern GL_R8_SNORM = 0x8F94

pattern GL_RASTERIZER_DISCARD = 0x8C89

pattern GL_READ_BUFFER = 0x0C02

pattern GL_READ_FRAMEBUFFER = 0x8CA8

pattern GL_READ_FRAMEBUFFER_BINDING = 0x8CAA

pattern GL_READ_ONLY = 0x88B8

pattern GL_READ_WRITE = 0x88BA

pattern GL_RED = 0x1903

pattern GL_RED_INTEGER = 0x8D94

pattern GL_RENDERBUFFER = 0x8D41

pattern GL_RENDERBUFFER_ALPHA_SIZE = 0x8D53

pattern GL_RENDERBUFFER_BINDING = 0x8CA7

pattern GL_RENDERBUFFER_BLUE_SIZE = 0x8D52

pattern GL_RENDERBUFFER_DEPTH_SIZE = 0x8D54

pattern GL_RENDERBUFFER_GREEN_SIZE = 0x8D51

pattern GL_RENDERBUFFER_HEIGHT = 0x8D43

pattern GL_RENDERBUFFER_INTERNAL_FORMAT = 0x8D44

pattern GL_RENDERBUFFER_RED_SIZE = 0x8D50

pattern GL_RENDERBUFFER_SAMPLES = 0x8CAB

pattern GL_RENDERBUFFER_STENCIL_SIZE = 0x8D55

pattern GL_RENDERBUFFER_WIDTH = 0x8D42

pattern GL_RENDERER = 0x1F01

pattern GL_REPEAT = 0x2901

pattern GL_REPLACE = 0x1E01

pattern GL_RG = 0x8227

pattern GL_RG16 = 0x822C

pattern GL_RG16F = 0x822F

pattern GL_RG16I = 0x8239

pattern GL_RG16UI = 0x823A

pattern GL_RG16_SNORM = 0x8F99

pattern GL_RG32F = 0x8230

pattern GL_RG32I = 0x823B

pattern GL_RG32UI = 0x823C

pattern GL_RG8 = 0x822B

pattern GL_RG8I = 0x8237

pattern GL_RG8UI = 0x8238

pattern GL_RG8_SNORM = 0x8F95

pattern GL_RGB = 0x1907

pattern GL_RGB10 = 0x8052

pattern GL_RGB10_A2 = 0x8059

pattern GL_RGB12 = 0x8053

pattern GL_RGB16 = 0x8054

pattern GL_RGB16F = 0x881B

pattern GL_RGB16I = 0x8D89

pattern GL_RGB16UI = 0x8D77

pattern GL_RGB16_SNORM = 0x8F9A

pattern GL_RGB32F = 0x8815

pattern GL_RGB32I = 0x8D83

pattern GL_RGB32UI = 0x8D71

pattern GL_RGB4 = 0x804F

pattern GL_RGB5 = 0x8050

pattern GL_RGB5_A1 = 0x8057

pattern GL_RGB8 = 0x8051

pattern GL_RGB8I = 0x8D8F

pattern GL_RGB8UI = 0x8D7D

pattern GL_RGB8_SNORM = 0x8F96

pattern GL_RGB9_E5 = 0x8C3D

pattern GL_RGBA = 0x1908

pattern GL_RGBA12 = 0x805A

pattern GL_RGBA16 = 0x805B

pattern GL_RGBA16F = 0x881A

pattern GL_RGBA16I = 0x8D88

pattern GL_RGBA16UI = 0x8D76

pattern GL_RGBA16_SNORM = 0x8F9B

pattern GL_RGBA2 = 0x8055

pattern GL_RGBA32F = 0x8814

pattern GL_RGBA32I = 0x8D82

pattern GL_RGBA32UI = 0x8D70

pattern GL_RGBA4 = 0x8056

pattern GL_RGBA8 = 0x8058

pattern GL_RGBA8I = 0x8D8E

pattern GL_RGBA8UI = 0x8D7C

pattern GL_RGBA8_SNORM = 0x8F97

pattern GL_RGBA_INTEGER = 0x8D99

pattern GL_RGB_INTEGER = 0x8D98

pattern GL_RG_INTEGER = 0x8228

pattern GL_RIGHT = 0x0407

pattern GL_SAMPLER_1D = 0x8B5D

pattern GL_SAMPLER_1D_ARRAY = 0x8DC0

pattern GL_SAMPLER_1D_ARRAY_SHADOW = 0x8DC3

pattern GL_SAMPLER_1D_SHADOW = 0x8B61

pattern GL_SAMPLER_2D = 0x8B5E

pattern GL_SAMPLER_2D_ARRAY = 0x8DC1

pattern GL_SAMPLER_2D_ARRAY_SHADOW = 0x8DC4

pattern GL_SAMPLER_2D_MULTISAMPLE = 0x9108

pattern GL_SAMPLER_2D_MULTISAMPLE_ARRAY = 0x910B

pattern GL_SAMPLER_2D_RECT = 0x8B63

pattern GL_SAMPLER_2D_RECT_SHADOW = 0x8B64

pattern GL_SAMPLER_2D_SHADOW = 0x8B62

pattern GL_SAMPLER_3D = 0x8B5F

pattern GL_SAMPLER_BUFFER = 0x8DC2

pattern GL_SAMPLER_CUBE = 0x8B60

pattern GL_SAMPLER_CUBE_SHADOW = 0x8DC5

pattern GL_SAMPLES = 0x80A9

pattern GL_SAMPLES_PASSED = 0x8914

pattern GL_SAMPLE_ALPHA_TO_COVERAGE = 0x809E

pattern GL_SAMPLE_ALPHA_TO_ONE = 0x809F

pattern GL_SAMPLE_BUFFERS = 0x80A8

pattern GL_SAMPLE_COVERAGE = 0x80A0

pattern GL_SAMPLE_COVERAGE_INVERT = 0x80AB

pattern GL_SAMPLE_COVERAGE_VALUE = 0x80AA

pattern GL_SAMPLE_MASK = 0x8E51

pattern GL_SAMPLE_MASK_VALUE = 0x8E52

pattern GL_SAMPLE_POSITION = 0x8E50

pattern GL_SCISSOR_BOX = 0x0C10

pattern GL_SCISSOR_TEST = 0x0C11

pattern GL_SEPARATE_ATTRIBS = 0x8C8D

pattern GL_SET = 0x150F

pattern GL_SHADER_SOURCE_LENGTH = 0x8B88

pattern GL_SHADER_TYPE = 0x8B4F

pattern GL_SHADING_LANGUAGE_VERSION = 0x8B8C

pattern GL_SHORT = 0x1402

pattern GL_SIGNALED = 0x9119

pattern GL_SIGNED_NORMALIZED = 0x8F9C

pattern GL_SMOOTH_LINE_WIDTH_GRANULARITY = 0x0B23

pattern GL_SMOOTH_LINE_WIDTH_RANGE = 0x0B22

pattern GL_SMOOTH_POINT_SIZE_GRANULARITY = 0x0B13

pattern GL_SMOOTH_POINT_SIZE_RANGE = 0x0B12

pattern GL_SRC1_ALPHA = 0x8589

pattern GL_SRC_ALPHA = 0x0302

pattern GL_SRC_ALPHA_SATURATE = 0x0308

pattern GL_SRC_COLOR = 0x0300

pattern GL_SRGB = 0x8C40

pattern GL_SRGB8 = 0x8C41

pattern GL_SRGB8_ALPHA8 = 0x8C43

pattern GL_SRGB_ALPHA = 0x8C42

pattern GL_STATIC_COPY = 0x88E6

pattern GL_STATIC_DRAW = 0x88E4

pattern GL_STATIC_READ = 0x88E5

pattern GL_STENCIL = 0x1802

pattern GL_STENCIL_ATTACHMENT = 0x8D20

pattern GL_STENCIL_BACK_FAIL = 0x8801

pattern GL_STENCIL_BACK_FUNC = 0x8800

pattern GL_STENCIL_BACK_PASS_DEPTH_FAIL = 0x8802

pattern GL_STENCIL_BACK_PASS_DEPTH_PASS = 0x8803

pattern GL_STENCIL_BACK_REF = 0x8CA3

pattern GL_STENCIL_BACK_VALUE_MASK = 0x8CA4

pattern GL_STENCIL_BACK_WRITEMASK = 0x8CA5

pattern GL_STENCIL_BUFFER_BIT = 0x00000400

pattern GL_STENCIL_CLEAR_VALUE = 0x0B91

pattern GL_STENCIL_FAIL = 0x0B94

pattern GL_STENCIL_FUNC = 0x0B92

pattern GL_STENCIL_INDEX = 0x1901

pattern GL_STENCIL_INDEX1 = 0x8D46

pattern GL_STENCIL_INDEX16 = 0x8D49

pattern GL_STENCIL_INDEX4 = 0x8D47

pattern GL_STENCIL_INDEX8 = 0x8D48

pattern GL_STENCIL_PASS_DEPTH_FAIL = 0x0B95

pattern GL_STENCIL_PASS_DEPTH_PASS = 0x0B96

pattern GL_STENCIL_REF = 0x0B97

pattern GL_STENCIL_TEST = 0x0B90

pattern GL_STENCIL_VALUE_MASK = 0x0B93

pattern GL_STENCIL_WRITEMASK = 0x0B98

pattern GL_STEREO = 0x0C33

pattern GL_STREAM_COPY = 0x88E2

pattern GL_STREAM_DRAW = 0x88E0

pattern GL_STREAM_READ = 0x88E1

pattern GL_SUBPIXEL_BITS = 0x0D50

pattern GL_SYNC_CONDITION = 0x9113

pattern GL_SYNC_FENCE = 0x9116

pattern GL_SYNC_FLAGS = 0x9115

pattern GL_SYNC_FLUSH_COMMANDS_BIT = 0x00000001

pattern GL_SYNC_GPU_COMMANDS_COMPLETE = 0x9117

pattern GL_SYNC_STATUS = 0x9114

pattern GL_TEXTURE = 0x1702

pattern GL_TEXTURE0 = 0x84C0

pattern GL_TEXTURE1 = 0x84C1

pattern GL_TEXTURE10 = 0x84CA

pattern GL_TEXTURE11 = 0x84CB

pattern GL_TEXTURE12 = 0x84CC

pattern GL_TEXTURE13 = 0x84CD

pattern GL_TEXTURE14 = 0x84CE

pattern GL_TEXTURE15 = 0x84CF

pattern GL_TEXTURE16 = 0x84D0

pattern GL_TEXTURE17 = 0x84D1

pattern GL_TEXTURE18 = 0x84D2

pattern GL_TEXTURE19 = 0x84D3

pattern GL_TEXTURE2 = 0x84C2

pattern GL_TEXTURE20 = 0x84D4

pattern GL_TEXTURE21 = 0x84D5

pattern GL_TEXTURE22 = 0x84D6

pattern GL_TEXTURE23 = 0x84D7

pattern GL_TEXTURE24 = 0x84D8

pattern GL_TEXTURE25 = 0x84D9

pattern GL_TEXTURE26 = 0x84DA

pattern GL_TEXTURE27 = 0x84DB

pattern GL_TEXTURE28 = 0x84DC

pattern GL_TEXTURE29 = 0x84DD

pattern GL_TEXTURE3 = 0x84C3

pattern GL_TEXTURE30 = 0x84DE

pattern GL_TEXTURE31 = 0x84DF

pattern GL_TEXTURE4 = 0x84C4

pattern GL_TEXTURE5 = 0x84C5

pattern GL_TEXTURE6 = 0x84C6

pattern GL_TEXTURE7 = 0x84C7

pattern GL_TEXTURE8 = 0x84C8

pattern GL_TEXTURE9 = 0x84C9

pattern GL_TEXTURE_1D = 0x0DE0

pattern GL_TEXTURE_1D_ARRAY = 0x8C18

pattern GL_TEXTURE_2D = 0x0DE1

pattern GL_TEXTURE_2D_ARRAY = 0x8C1A

pattern GL_TEXTURE_2D_MULTISAMPLE = 0x9100

pattern GL_TEXTURE_2D_MULTISAMPLE_ARRAY = 0x9102

pattern GL_TEXTURE_3D = 0x806F

pattern GL_TEXTURE_ALPHA_SIZE = 0x805F

pattern GL_TEXTURE_ALPHA_TYPE = 0x8C13

pattern GL_TEXTURE_BASE_LEVEL = 0x813C

pattern GL_TEXTURE_BINDING_1D = 0x8068

pattern GL_TEXTURE_BINDING_1D_ARRAY = 0x8C1C

pattern GL_TEXTURE_BINDING_2D = 0x8069

pattern GL_TEXTURE_BINDING_2D_ARRAY = 0x8C1D

pattern GL_TEXTURE_BINDING_2D_MULTISAMPLE = 0x9104

pattern GL_TEXTURE_BINDING_2D_MULTISAMPLE_ARRAY = 0x9105

pattern GL_TEXTURE_BINDING_3D = 0x806A

pattern GL_TEXTURE_BINDING_BUFFER = 0x8C2C

pattern GL_TEXTURE_BINDING_CUBE_MAP = 0x8514

pattern GL_TEXTURE_BINDING_RECTANGLE = 0x84F6

pattern GL_TEXTURE_BLUE_SIZE = 0x805E

pattern GL_TEXTURE_BLUE_TYPE = 0x8C12

pattern GL_TEXTURE_BORDER_COLOR = 0x1004

pattern GL_TEXTURE_BUFFER = 0x8C2A

pattern GL_TEXTURE_BUFFER_DATA_STORE_BINDING = 0x8C2D

pattern GL_TEXTURE_COMPARE_FUNC = 0x884D

pattern GL_TEXTURE_COMPARE_MODE = 0x884C

pattern GL_TEXTURE_COMPRESSED = 0x86A1

pattern GL_TEXTURE_COMPRESSED_IMAGE_SIZE = 0x86A0

pattern GL_TEXTURE_COMPRESSION_HINT = 0x84EF

pattern GL_TEXTURE_CUBE_MAP = 0x8513

pattern GL_TEXTURE_CUBE_MAP_NEGATIVE_X = 0x8516

pattern GL_TEXTURE_CUBE_MAP_NEGATIVE_Y = 0x8518

pattern GL_TEXTURE_CUBE_MAP_NEGATIVE_Z = 0x851A

pattern GL_TEXTURE_CUBE_MAP_POSITIVE_X = 0x8515

pattern GL_TEXTURE_CUBE_MAP_POSITIVE_Y = 0x8517

pattern GL_TEXTURE_CUBE_MAP_POSITIVE_Z = 0x8519

pattern GL_TEXTURE_CUBE_MAP_SEAMLESS = 0x884F

pattern GL_TEXTURE_DEPTH = 0x8071

pattern GL_TEXTURE_DEPTH_SIZE = 0x884A

pattern GL_TEXTURE_DEPTH_TYPE = 0x8C16

pattern GL_TEXTURE_FIXED_SAMPLE_LOCATIONS = 0x9107

pattern GL_TEXTURE_GREEN_SIZE = 0x805D

pattern GL_TEXTURE_GREEN_TYPE = 0x8C11

pattern GL_TEXTURE_HEIGHT = 0x1001

pattern GL_TEXTURE_INTERNAL_FORMAT = 0x1003

pattern GL_TEXTURE_LOD_BIAS = 0x8501

pattern GL_TEXTURE_MAG_FILTER = 0x2800

pattern GL_TEXTURE_MAX_LEVEL = 0x813D

pattern GL_TEXTURE_MAX_LOD = 0x813B

pattern GL_TEXTURE_MIN_FILTER = 0x2801

pattern GL_TEXTURE_MIN_LOD = 0x813A

pattern GL_TEXTURE_RECTANGLE = 0x84F5

pattern GL_TEXTURE_RED_SIZE = 0x805C

pattern GL_TEXTURE_RED_TYPE = 0x8C10

pattern GL_TEXTURE_SAMPLES = 0x9106

pattern GL_TEXTURE_SHARED_SIZE = 0x8C3F

pattern GL_TEXTURE_STENCIL_SIZE = 0x88F1

pattern GL_TEXTURE_WIDTH = 0x1000

pattern GL_TEXTURE_WRAP_R = 0x8072

pattern GL_TEXTURE_WRAP_S = 0x2802

pattern GL_TEXTURE_WRAP_T = 0x2803

pattern GL_TIMEOUT_EXPIRED = 0x911B

pattern GL_TIMEOUT_IGNORED = 0xFFFFFFFFFFFFFFFF

pattern GL_TRANSFORM_FEEDBACK_BUFFER = 0x8C8E

pattern GL_TRANSFORM_FEEDBACK_BUFFER_BINDING = 0x8C8F

pattern GL_TRANSFORM_FEEDBACK_BUFFER_MODE = 0x8C7F

pattern GL_TRANSFORM_FEEDBACK_BUFFER_SIZE = 0x8C85

pattern GL_TRANSFORM_FEEDBACK_BUFFER_START = 0x8C84

pattern GL_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN = 0x8C88

pattern GL_TRANSFORM_FEEDBACK_VARYINGS = 0x8C83

pattern GL_TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH = 0x8C76

pattern GL_TRIANGLES = 0x0004

pattern GL_TRIANGLES_ADJACENCY = 0x000C

pattern GL_TRIANGLE_FAN = 0x0006

pattern GL_TRIANGLE_STRIP = 0x0005

pattern GL_TRIANGLE_STRIP_ADJACENCY = 0x000D

pattern GL_TRUE = 1

pattern GL_UNIFORM_ARRAY_STRIDE = 0x8A3C

pattern GL_UNIFORM_BLOCK_ACTIVE_UNIFORMS = 0x8A42

pattern GL_UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES = 0x8A43

pattern GL_UNIFORM_BLOCK_BINDING = 0x8A3F

pattern GL_UNIFORM_BLOCK_DATA_SIZE = 0x8A40

pattern GL_UNIFORM_BLOCK_INDEX = 0x8A3A

pattern GL_UNIFORM_BLOCK_NAME_LENGTH = 0x8A41

pattern GL_UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER = 0x8A46

pattern GL_UNIFORM_BLOCK_REFERENCED_BY_GEOMETRY_SHADER = 0x8A45

pattern GL_UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER = 0x8A44

pattern GL_UNIFORM_BUFFER = 0x8A11

pattern GL_UNIFORM_BUFFER_BINDING = 0x8A28

pattern GL_UNIFORM_BUFFER_OFFSET_ALIGNMENT = 0x8A34

pattern GL_UNIFORM_BUFFER_SIZE = 0x8A2A

pattern GL_UNIFORM_BUFFER_START = 0x8A29

pattern GL_UNIFORM_IS_ROW_MAJOR = 0x8A3E

pattern GL_UNIFORM_MATRIX_STRIDE = 0x8A3D

pattern GL_UNIFORM_NAME_LENGTH = 0x8A39

pattern GL_UNIFORM_OFFSET = 0x8A3B

pattern GL_UNIFORM_SIZE = 0x8A38

pattern GL_UNIFORM_TYPE = 0x8A37

pattern GL_UNPACK_ALIGNMENT = 0x0CF5

pattern GL_UNPACK_IMAGE_HEIGHT = 0x806E

pattern GL_UNPACK_LSB_FIRST = 0x0CF1

pattern GL_UNPACK_ROW_LENGTH = 0x0CF2

pattern GL_UNPACK_SKIP_IMAGES = 0x806D

pattern GL_UNPACK_SKIP_PIXELS = 0x0CF4

pattern GL_UNPACK_SKIP_ROWS = 0x0CF3

pattern GL_UNPACK_SWAP_BYTES = 0x0CF0

pattern GL_UNSIGNALED = 0x9118

pattern GL_UNSIGNED_BYTE = 0x1401

pattern GL_UNSIGNED_BYTE_2_3_3_REV = 0x8362

pattern GL_UNSIGNED_BYTE_3_3_2 = 0x8032

pattern GL_UNSIGNED_INT = 0x1405

pattern GL_UNSIGNED_INT_10F_11F_11F_REV = 0x8C3B

pattern GL_UNSIGNED_INT_10_10_10_2 = 0x8036

pattern GL_UNSIGNED_INT_24_8 = 0x84FA

pattern GL_UNSIGNED_INT_2_10_10_10_REV = 0x8368

pattern GL_UNSIGNED_INT_5_9_9_9_REV = 0x8C3E

pattern GL_UNSIGNED_INT_8_8_8_8 = 0x8035

pattern GL_UNSIGNED_INT_8_8_8_8_REV = 0x8367

pattern GL_UNSIGNED_INT_SAMPLER_1D = 0x8DD1

pattern GL_UNSIGNED_INT_SAMPLER_1D_ARRAY = 0x8DD6

pattern GL_UNSIGNED_INT_SAMPLER_2D = 0x8DD2

pattern GL_UNSIGNED_INT_SAMPLER_2D_ARRAY = 0x8DD7

pattern GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE = 0x910A

pattern GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE_ARRAY = 0x910D

pattern GL_UNSIGNED_INT_SAMPLER_2D_RECT = 0x8DD5

pattern GL_UNSIGNED_INT_SAMPLER_3D = 0x8DD3

pattern GL_UNSIGNED_INT_SAMPLER_BUFFER = 0x8DD8

pattern GL_UNSIGNED_INT_SAMPLER_CUBE = 0x8DD4

pattern GL_UNSIGNED_INT_VEC2 = 0x8DC6

pattern GL_UNSIGNED_INT_VEC3 = 0x8DC7

pattern GL_UNSIGNED_INT_VEC4 = 0x8DC8

pattern GL_UNSIGNED_NORMALIZED = 0x8C17

pattern GL_UNSIGNED_SHORT = 0x1403

pattern GL_UNSIGNED_SHORT_1_5_5_5_REV = 0x8366

pattern GL_UNSIGNED_SHORT_4_4_4_4 = 0x8033

pattern GL_UNSIGNED_SHORT_4_4_4_4_REV = 0x8365

pattern GL_UNSIGNED_SHORT_5_5_5_1 = 0x8034

pattern GL_UNSIGNED_SHORT_5_6_5 = 0x8363

pattern GL_UNSIGNED_SHORT_5_6_5_REV = 0x8364

pattern GL_UPPER_LEFT = 0x8CA2

pattern GL_VALIDATE_STATUS = 0x8B83

pattern GL_VENDOR = 0x1F00

pattern GL_VERSION = 0x1F02

pattern GL_VERTEX_ARRAY_BINDING = 0x85B5

pattern GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING = 0x889F

pattern GL_VERTEX_ATTRIB_ARRAY_ENABLED = 0x8622

pattern GL_VERTEX_ATTRIB_ARRAY_INTEGER = 0x88FD

pattern GL_VERTEX_ATTRIB_ARRAY_NORMALIZED = 0x886A

pattern GL_VERTEX_ATTRIB_ARRAY_POINTER = 0x8645

pattern GL_VERTEX_ATTRIB_ARRAY_SIZE = 0x8623

pattern GL_VERTEX_ATTRIB_ARRAY_STRIDE = 0x8624

pattern GL_VERTEX_ATTRIB_ARRAY_TYPE = 0x8625

pattern GL_VERTEX_PROGRAM_POINT_SIZE = 0x8642

pattern GL_VERTEX_SHADER = 0x8B31

pattern GL_VIEWPORT = 0x0BA2

pattern GL_WAIT_FAILED = 0x911D

pattern GL_WRITE_ONLY = 0x88B9

pattern GL_XOR = 0x1506

pattern GL_ZERO = 0

pattern GL_ANY_SAMPLES_PASSED = 0x8C2F

pattern GL_INT_2_10_10_10_REV = 0x8D9F

pattern GL_MAX_DUAL_SOURCE_DRAW_BUFFERS = 0x88FC

pattern GL_ONE_MINUS_SRC1_ALPHA = 0x88FB

pattern GL_ONE_MINUS_SRC1_COLOR = 0x88FA

pattern GL_RGB10_A2UI = 0x906F

pattern GL_SAMPLER_BINDING = 0x8919

pattern GL_SRC1_COLOR = 0x88F9

pattern GL_TEXTURE_SWIZZLE_A = 0x8E45

pattern GL_TEXTURE_SWIZZLE_B = 0x8E44

pattern GL_TEXTURE_SWIZZLE_G = 0x8E43

pattern GL_TEXTURE_SWIZZLE_R = 0x8E42

pattern GL_TEXTURE_SWIZZLE_RGBA = 0x8E46

pattern GL_TIMESTAMP = 0x8E28

pattern GL_TIME_ELAPSED = 0x88BF

pattern GL_VERTEX_ATTRIB_ARRAY_DIVISOR = 0x88FE

pattern GL_ACTIVE_SUBROUTINES = 0x8DE5

pattern GL_ACTIVE_SUBROUTINE_MAX_LENGTH = 0x8E48

pattern GL_ACTIVE_SUBROUTINE_UNIFORMS = 0x8DE6

pattern GL_ACTIVE_SUBROUTINE_UNIFORM_LOCATIONS = 0x8E47

pattern GL_ACTIVE_SUBROUTINE_UNIFORM_MAX_LENGTH = 0x8E49

pattern GL_COMPATIBLE_SUBROUTINES = 0x8E4B

pattern GL_DOUBLE_MAT2 = 0x8F46

pattern GL_DOUBLE_MAT2x3 = 0x8F49

pattern GL_DOUBLE_MAT2x4 = 0x8F4A

pattern GL_DOUBLE_MAT3 = 0x8F47

pattern GL_DOUBLE_MAT3x2 = 0x8F4B

pattern GL_DOUBLE_MAT3x4 = 0x8F4C

pattern GL_DOUBLE_MAT4 = 0x8F48

pattern GL_DOUBLE_MAT4x2 = 0x8F4D

pattern GL_DOUBLE_MAT4x3 = 0x8F4E

pattern GL_DOUBLE_VEC2 = 0x8FFC

pattern GL_DOUBLE_VEC3 = 0x8FFD

pattern GL_DOUBLE_VEC4 = 0x8FFE

pattern GL_DRAW_INDIRECT_BUFFER = 0x8F3F

pattern GL_DRAW_INDIRECT_BUFFER_BINDING = 0x8F43

pattern GL_FRACTIONAL_EVEN = 0x8E7C

pattern GL_FRACTIONAL_ODD = 0x8E7B

pattern GL_FRAGMENT_INTERPOLATION_OFFSET_BITS = 0x8E5D

pattern GL_GEOMETRY_SHADER_INVOCATIONS = 0x887F

pattern GL_INT_SAMPLER_CUBE_MAP_ARRAY = 0x900E

pattern GL_ISOLINES = 0x8E7A

pattern GL_MAX_COMBINED_TESS_CONTROL_UNIFORM_COMPONENTS = 0x8E1E

pattern GL_MAX_COMBINED_TESS_EVALUATION_UNIFORM_COMPONENTS = 0x8E1F

pattern GL_MAX_FRAGMENT_INTERPOLATION_OFFSET = 0x8E5C

pattern GL_MAX_GEOMETRY_SHADER_INVOCATIONS = 0x8E5A

pattern GL_MAX_PATCH_VERTICES = 0x8E7D

pattern GL_MAX_PROGRAM_TEXTURE_GATHER_OFFSET = 0x8E5F

pattern GL_MAX_SUBROUTINES = 0x8DE7

pattern GL_MAX_SUBROUTINE_UNIFORM_LOCATIONS = 0x8DE8

pattern GL_MAX_TESS_CONTROL_INPUT_COMPONENTS = 0x886C

pattern GL_MAX_TESS_CONTROL_OUTPUT_COMPONENTS = 0x8E83

pattern GL_MAX_TESS_CONTROL_TEXTURE_IMAGE_UNITS = 0x8E81

pattern GL_MAX_TESS_CONTROL_TOTAL_OUTPUT_COMPONENTS = 0x8E85

pattern GL_MAX_TESS_CONTROL_UNIFORM_BLOCKS = 0x8E89

pattern GL_MAX_TESS_CONTROL_UNIFORM_COMPONENTS = 0x8E7F

pattern GL_MAX_TESS_EVALUATION_INPUT_COMPONENTS = 0x886D

pattern GL_MAX_TESS_EVALUATION_OUTPUT_COMPONENTS = 0x8E86

pattern GL_MAX_TESS_EVALUATION_TEXTURE_IMAGE_UNITS = 0x8E82

pattern GL_MAX_TESS_EVALUATION_UNIFORM_BLOCKS = 0x8E8A

pattern GL_MAX_TESS_EVALUATION_UNIFORM_COMPONENTS = 0x8E80

pattern GL_MAX_TESS_GEN_LEVEL = 0x8E7E

pattern GL_MAX_TESS_PATCH_COMPONENTS = 0x8E84

pattern GL_MAX_TRANSFORM_FEEDBACK_BUFFERS = 0x8E70

pattern GL_MAX_VERTEX_STREAMS = 0x8E71

pattern GL_MIN_FRAGMENT_INTERPOLATION_OFFSET = 0x8E5B

pattern GL_MIN_PROGRAM_TEXTURE_GATHER_OFFSET = 0x8E5E

pattern GL_MIN_SAMPLE_SHADING_VALUE = 0x8C37

pattern GL_NUM_COMPATIBLE_SUBROUTINES = 0x8E4A

pattern GL_PATCHES = 0x000E

pattern GL_PATCH_DEFAULT_INNER_LEVEL = 0x8E73

pattern GL_PATCH_DEFAULT_OUTER_LEVEL = 0x8E74

pattern GL_PATCH_VERTICES = 0x8E72

pattern GL_SAMPLER_CUBE_MAP_ARRAY = 0x900C

pattern GL_SAMPLER_CUBE_MAP_ARRAY_SHADOW = 0x900D

pattern GL_SAMPLE_SHADING = 0x8C36

pattern GL_TESS_CONTROL_OUTPUT_VERTICES = 0x8E75

pattern GL_TESS_CONTROL_SHADER = 0x8E88

pattern GL_TESS_EVALUATION_SHADER = 0x8E87

pattern GL_TESS_GEN_MODE = 0x8E76

pattern GL_TESS_GEN_POINT_MODE = 0x8E79

pattern GL_TESS_GEN_SPACING = 0x8E77

pattern GL_TESS_GEN_VERTEX_ORDER = 0x8E78

pattern GL_TEXTURE_BINDING_CUBE_MAP_ARRAY = 0x900A

pattern GL_TEXTURE_CUBE_MAP_ARRAY = 0x9009

pattern GL_TRANSFORM_FEEDBACK = 0x8E22

pattern GL_TRANSFORM_FEEDBACK_BINDING = 0x8E25

pattern GL_TRANSFORM_FEEDBACK_BUFFER_ACTIVE = 0x8E24

pattern GL_TRANSFORM_FEEDBACK_BUFFER_PAUSED = 0x8E23

pattern GL_UNIFORM_BLOCK_REFERENCED_BY_TESS_CONTROL_SHADER = 0x84F0

pattern GL_UNIFORM_BLOCK_REFERENCED_BY_TESS_EVALUATION_SHADER = 0x84F1

pattern GL_UNSIGNED_INT_SAMPLER_CUBE_MAP_ARRAY = 0x900F

pattern GL_ACTIVE_PROGRAM = 0x8259

pattern GL_ALL_SHADER_BITS = 0xFFFFFFFF

pattern GL_FIXED = 0x140C

pattern GL_FRAGMENT_SHADER_BIT = 0x00000002

pattern GL_GEOMETRY_SHADER_BIT = 0x00000004

pattern GL_HIGH_FLOAT = 0x8DF2

pattern GL_HIGH_INT = 0x8DF5

pattern GL_IMPLEMENTATION_COLOR_READ_FORMAT = 0x8B9B

pattern GL_IMPLEMENTATION_COLOR_READ_TYPE = 0x8B9A

pattern GL_LAYER_PROVOKING_VERTEX = 0x825E

pattern GL_LOW_FLOAT = 0x8DF0

pattern GL_LOW_INT = 0x8DF3

pattern GL_MAX_FRAGMENT_UNIFORM_VECTORS = 0x8DFD

pattern GL_MAX_VARYING_VECTORS = 0x8DFC

pattern GL_MAX_VERTEX_UNIFORM_VECTORS = 0x8DFB

pattern GL_MAX_VIEWPORTS = 0x825B

pattern GL_MEDIUM_FLOAT = 0x8DF1

pattern GL_MEDIUM_INT = 0x8DF4

pattern GL_NUM_PROGRAM_BINARY_FORMATS = 0x87FE

pattern GL_NUM_SHADER_BINARY_FORMATS = 0x8DF9

pattern GL_PROGRAM_BINARY_FORMATS = 0x87FF

pattern GL_PROGRAM_BINARY_LENGTH = 0x8741

pattern GL_PROGRAM_BINARY_RETRIEVABLE_HINT = 0x8257

pattern GL_PROGRAM_PIPELINE_BINDING = 0x825A

pattern GL_PROGRAM_SEPARABLE = 0x8258

pattern GL_RGB565 = 0x8D62

pattern GL_SHADER_BINARY_FORMATS = 0x8DF8

pattern GL_SHADER_COMPILER = 0x8DFA

pattern GL_TESS_CONTROL_SHADER_BIT = 0x00000008

pattern GL_TESS_EVALUATION_SHADER_BIT = 0x00000010

pattern GL_UNDEFINED_VERTEX = 0x8260

pattern GL_VERTEX_SHADER_BIT = 0x00000001

pattern GL_VIEWPORT_BOUNDS_RANGE = 0x825D

pattern GL_VIEWPORT_INDEX_PROVOKING_VERTEX = 0x825F

pattern GL_VIEWPORT_SUBPIXEL_BITS = 0x825C

pattern GL_ACTIVE_ATOMIC_COUNTER_BUFFERS = 0x92D9

pattern GL_ALL_BARRIER_BITS = 0xFFFFFFFF

pattern GL_ATOMIC_COUNTER_BARRIER_BIT = 0x00001000

pattern GL_ATOMIC_COUNTER_BUFFER = 0x92C0

pattern GL_ATOMIC_COUNTER_BUFFER_ACTIVE_ATOMIC_COUNTERS = 0x92C5

pattern GL_ATOMIC_COUNTER_BUFFER_ACTIVE_ATOMIC_COUNTER_INDICES = 0x92C6

pattern GL_ATOMIC_COUNTER_BUFFER_BINDING = 0x92C1

pattern GL_ATOMIC_COUNTER_BUFFER_DATA_SIZE = 0x92C4

pattern GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_FRAGMENT_SHADER = 0x92CB

pattern GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_GEOMETRY_SHADER = 0x92CA

pattern GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_TESS_CONTROL_SHADER = 0x92C8

pattern GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_TESS_EVALUATION_SHADER = 0x92C9

pattern GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_VERTEX_SHADER = 0x92C7

pattern GL_ATOMIC_COUNTER_BUFFER_SIZE = 0x92C3

pattern GL_ATOMIC_COUNTER_BUFFER_START = 0x92C2

pattern GL_BUFFER_UPDATE_BARRIER_BIT = 0x00000200

pattern GL_COMMAND_BARRIER_BIT = 0x00000040

pattern GL_COPY_READ_BUFFER_BINDING = 0x8F36

pattern GL_COPY_WRITE_BUFFER_BINDING = 0x8F37

pattern GL_ELEMENT_ARRAY_BARRIER_BIT = 0x00000002

pattern GL_FRAMEBUFFER_BARRIER_BIT = 0x00000400

pattern GL_IMAGE_1D = 0x904C

pattern GL_IMAGE_1D_ARRAY = 0x9052

pattern GL_IMAGE_2D = 0x904D

pattern GL_IMAGE_2D_ARRAY = 0x9053

pattern GL_IMAGE_2D_MULTISAMPLE = 0x9055

pattern GL_IMAGE_2D_MULTISAMPLE_ARRAY = 0x9056

pattern GL_IMAGE_2D_RECT = 0x904F

pattern GL_IMAGE_3D = 0x904E

pattern GL_IMAGE_BINDING_ACCESS = 0x8F3E

pattern GL_IMAGE_BINDING_FORMAT = 0x906E

pattern GL_IMAGE_BINDING_LAYER = 0x8F3D

pattern GL_IMAGE_BINDING_LAYERED = 0x8F3C

pattern GL_IMAGE_BINDING_LEVEL = 0x8F3B

pattern GL_IMAGE_BINDING_NAME = 0x8F3A

pattern GL_IMAGE_BUFFER = 0x9051

pattern GL_IMAGE_CUBE = 0x9050

pattern GL_IMAGE_CUBE_MAP_ARRAY = 0x9054

pattern GL_IMAGE_FORMAT_COMPATIBILITY_BY_CLASS = 0x90C9

pattern GL_IMAGE_FORMAT_COMPATIBILITY_BY_SIZE = 0x90C8

pattern GL_IMAGE_FORMAT_COMPATIBILITY_TYPE = 0x90C7

pattern GL_INT_IMAGE_1D = 0x9057

pattern GL_INT_IMAGE_1D_ARRAY = 0x905D

pattern GL_INT_IMAGE_2D = 0x9058

pattern GL_INT_IMAGE_2D_ARRAY = 0x905E

pattern GL_INT_IMAGE_2D_MULTISAMPLE = 0x9060

pattern GL_INT_IMAGE_2D_MULTISAMPLE_ARRAY = 0x9061

pattern GL_INT_IMAGE_2D_RECT = 0x905A

pattern GL_INT_IMAGE_3D = 0x9059

pattern GL_INT_IMAGE_BUFFER = 0x905C

pattern GL_INT_IMAGE_CUBE = 0x905B

pattern GL_INT_IMAGE_CUBE_MAP_ARRAY = 0x905F

pattern GL_MAX_ATOMIC_COUNTER_BUFFER_BINDINGS = 0x92DC

pattern GL_MAX_ATOMIC_COUNTER_BUFFER_SIZE = 0x92D8

pattern GL_MAX_COMBINED_ATOMIC_COUNTERS = 0x92D7

pattern GL_MAX_COMBINED_ATOMIC_COUNTER_BUFFERS = 0x92D1

pattern GL_MAX_COMBINED_IMAGE_UNIFORMS = 0x90CF

pattern GL_MAX_COMBINED_IMAGE_UNITS_AND_FRAGMENT_OUTPUTS = 0x8F39

pattern GL_MAX_FRAGMENT_ATOMIC_COUNTERS = 0x92D6

pattern GL_MAX_FRAGMENT_ATOMIC_COUNTER_BUFFERS = 0x92D0

pattern GL_MAX_FRAGMENT_IMAGE_UNIFORMS = 0x90CE

pattern GL_MAX_GEOMETRY_ATOMIC_COUNTERS = 0x92D5

pattern GL_MAX_GEOMETRY_ATOMIC_COUNTER_BUFFERS = 0x92CF

pattern GL_MAX_GEOMETRY_IMAGE_UNIFORMS = 0x90CD

pattern GL_MAX_IMAGE_SAMPLES = 0x906D

pattern GL_MAX_IMAGE_UNITS = 0x8F38

pattern GL_MAX_TESS_CONTROL_ATOMIC_COUNTERS = 0x92D3

pattern GL_MAX_TESS_CONTROL_ATOMIC_COUNTER_BUFFERS = 0x92CD

pattern GL_MAX_TESS_CONTROL_IMAGE_UNIFORMS = 0x90CB

pattern GL_MAX_TESS_EVALUATION_ATOMIC_COUNTERS = 0x92D4

pattern GL_MAX_TESS_EVALUATION_ATOMIC_COUNTER_BUFFERS = 0x92CE

pattern GL_MAX_TESS_EVALUATION_IMAGE_UNIFORMS = 0x90CC

pattern GL_MAX_VERTEX_ATOMIC_COUNTERS = 0x92D2

pattern GL_MAX_VERTEX_ATOMIC_COUNTER_BUFFERS = 0x92CC

pattern GL_MAX_VERTEX_IMAGE_UNIFORMS = 0x90CA

pattern GL_MIN_MAP_BUFFER_ALIGNMENT = 0x90BC

pattern GL_NUM_SAMPLE_COUNTS = 0x9380

pattern GL_PACK_COMPRESSED_BLOCK_DEPTH = 0x912D

pattern GL_PACK_COMPRESSED_BLOCK_HEIGHT = 0x912C

pattern GL_PACK_COMPRESSED_BLOCK_SIZE = 0x912E

pattern GL_PACK_COMPRESSED_BLOCK_WIDTH = 0x912B

pattern GL_PIXEL_BUFFER_BARRIER_BIT = 0x00000080

pattern GL_SHADER_IMAGE_ACCESS_BARRIER_BIT = 0x00000020

pattern GL_TEXTURE_FETCH_BARRIER_BIT = 0x00000008

pattern GL_TEXTURE_IMMUTABLE_FORMAT = 0x912F

pattern GL_TEXTURE_UPDATE_BARRIER_BIT = 0x00000100

pattern GL_TRANSFORM_FEEDBACK_ACTIVE = 0x8E24

pattern GL_TRANSFORM_FEEDBACK_BARRIER_BIT = 0x00000800

pattern GL_TRANSFORM_FEEDBACK_PAUSED = 0x8E23

pattern GL_UNIFORM_ATOMIC_COUNTER_BUFFER_INDEX = 0x92DA

pattern GL_UNIFORM_BARRIER_BIT = 0x00000004

pattern GL_UNPACK_COMPRESSED_BLOCK_DEPTH = 0x9129

pattern GL_UNPACK_COMPRESSED_BLOCK_HEIGHT = 0x9128

pattern GL_UNPACK_COMPRESSED_BLOCK_SIZE = 0x912A

pattern GL_UNPACK_COMPRESSED_BLOCK_WIDTH = 0x9127

pattern GL_UNSIGNED_INT_ATOMIC_COUNTER = 0x92DB

pattern GL_UNSIGNED_INT_IMAGE_1D = 0x9062

pattern GL_UNSIGNED_INT_IMAGE_1D_ARRAY = 0x9068

pattern GL_UNSIGNED_INT_IMAGE_2D = 0x9063

pattern GL_UNSIGNED_INT_IMAGE_2D_ARRAY = 0x9069

pattern GL_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE = 0x906B

pattern GL_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE_ARRAY = 0x906C

pattern GL_UNSIGNED_INT_IMAGE_2D_RECT = 0x9065

pattern GL_UNSIGNED_INT_IMAGE_3D = 0x9064

pattern GL_UNSIGNED_INT_IMAGE_BUFFER = 0x9067

pattern GL_UNSIGNED_INT_IMAGE_CUBE = 0x9066

pattern GL_UNSIGNED_INT_IMAGE_CUBE_MAP_ARRAY = 0x906A

pattern GL_VERTEX_ATTRIB_ARRAY_BARRIER_BIT = 0x00000001

pattern GL_ACTIVE_RESOURCES = 0x92F5

pattern GL_ACTIVE_VARIABLES = 0x9305

pattern GL_ANY_SAMPLES_PASSED_CONSERVATIVE = 0x8D6A

pattern GL_ARRAY_SIZE = 0x92FB

pattern GL_ARRAY_STRIDE = 0x92FE

pattern GL_ATOMIC_COUNTER_BUFFER_INDEX = 0x9301

pattern GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_COMPUTE_SHADER = 0x90ED

pattern GL_AUTO_GENERATE_MIPMAP = 0x8295

pattern GL_BLOCK_INDEX = 0x92FD

pattern GL_BUFFER = 0x82E0

pattern GL_BUFFER_BINDING = 0x9302

pattern GL_BUFFER_DATA_SIZE = 0x9303

pattern GL_BUFFER_VARIABLE = 0x92E5

pattern GL_CAVEAT_SUPPORT = 0x82B8

pattern GL_CLEAR_BUFFER = 0x82B4

pattern GL_COLOR_COMPONENTS = 0x8283

pattern GL_COLOR_ENCODING = 0x8296

pattern GL_COLOR_RENDERABLE = 0x8286

pattern GL_COMPRESSED_R11_EAC = 0x9270

pattern GL_COMPRESSED_RG11_EAC = 0x9272

pattern GL_COMPRESSED_RGB8_ETC2 = 0x9274

pattern GL_COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2 = 0x9276

pattern GL_COMPRESSED_RGBA8_ETC2_EAC = 0x9278

pattern GL_COMPRESSED_SIGNED_R11_EAC = 0x9271

pattern GL_COMPRESSED_SIGNED_RG11_EAC = 0x9273

pattern GL_COMPRESSED_SRGB8_ALPHA8_ETC2_EAC = 0x9279

pattern GL_COMPRESSED_SRGB8_ETC2 = 0x9275

pattern GL_COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2 = 0x9277

pattern GL_COMPUTE_SHADER = 0x91B9

pattern GL_COMPUTE_SHADER_BIT = 0x00000020

pattern GL_COMPUTE_SUBROUTINE = 0x92ED

pattern GL_COMPUTE_SUBROUTINE_UNIFORM = 0x92F3

pattern GL_COMPUTE_TEXTURE = 0x82A0

pattern GL_COMPUTE_WORK_GROUP_SIZE = 0x8267

pattern GL_CONTEXT_FLAG_DEBUG_BIT = 0x00000002

pattern GL_DEBUG_CALLBACK_FUNCTION = 0x8244

pattern GL_DEBUG_CALLBACK_USER_PARAM = 0x8245

pattern GL_DEBUG_GROUP_STACK_DEPTH = 0x826D

pattern GL_DEBUG_LOGGED_MESSAGES = 0x9145

pattern GL_DEBUG_NEXT_LOGGED_MESSAGE_LENGTH = 0x8243

pattern GL_DEBUG_OUTPUT = 0x92E0

pattern GL_DEBUG_OUTPUT_SYNCHRONOUS = 0x8242

pattern GL_DEBUG_SEVERITY_HIGH = 0x9146

pattern GL_DEBUG_SEVERITY_LOW = 0x9148

pattern GL_DEBUG_SEVERITY_MEDIUM = 0x9147

pattern GL_DEBUG_SEVERITY_NOTIFICATION = 0x826B

pattern GL_DEBUG_SOURCE_API = 0x8246

pattern GL_DEBUG_SOURCE_APPLICATION = 0x824A

pattern GL_DEBUG_SOURCE_OTHER = 0x824B

pattern GL_DEBUG_SOURCE_SHADER_COMPILER = 0x8248

pattern GL_DEBUG_SOURCE_THIRD_PARTY = 0x8249

pattern GL_DEBUG_SOURCE_WINDOW_SYSTEM = 0x8247

pattern GL_DEBUG_TYPE_DEPRECATED_BEHAVIOR = 0x824D

pattern GL_DEBUG_TYPE_ERROR = 0x824C

pattern GL_DEBUG_TYPE_MARKER = 0x8268

pattern GL_DEBUG_TYPE_OTHER = 0x8251

pattern GL_DEBUG_TYPE_PERFORMANCE = 0x8250

pattern GL_DEBUG_TYPE_POP_GROUP = 0x826A

pattern GL_DEBUG_TYPE_PORTABILITY = 0x824F

pattern GL_DEBUG_TYPE_PUSH_GROUP = 0x8269

pattern GL_DEBUG_TYPE_UNDEFINED_BEHAVIOR = 0x824E

pattern GL_DEPTH_COMPONENTS = 0x8284

pattern GL_DEPTH_RENDERABLE = 0x8287

pattern GL_DEPTH_STENCIL_TEXTURE_MODE = 0x90EA

pattern GL_DISPATCH_INDIRECT_BUFFER = 0x90EE

pattern GL_DISPATCH_INDIRECT_BUFFER_BINDING = 0x90EF

pattern GL_FILTER = 0x829A

pattern GL_FRAGMENT_SUBROUTINE = 0x92EC

pattern GL_FRAGMENT_SUBROUTINE_UNIFORM = 0x92F2

pattern GL_FRAGMENT_TEXTURE = 0x829F

pattern GL_FRAMEBUFFER_BLEND = 0x828B

pattern GL_FRAMEBUFFER_DEFAULT_FIXED_SAMPLE_LOCATIONS = 0x9314

pattern GL_FRAMEBUFFER_DEFAULT_HEIGHT = 0x9311

pattern GL_FRAMEBUFFER_DEFAULT_LAYERS = 0x9312

pattern GL_FRAMEBUFFER_DEFAULT_SAMPLES = 0x9313

pattern GL_FRAMEBUFFER_DEFAULT_WIDTH = 0x9310

pattern GL_FRAMEBUFFER_RENDERABLE = 0x8289

pattern GL_FRAMEBUFFER_RENDERABLE_LAYERED = 0x828A

pattern GL_FULL_SUPPORT = 0x82B7

pattern GL_GEOMETRY_SUBROUTINE = 0x92EB

pattern GL_GEOMETRY_SUBROUTINE_UNIFORM = 0x92F1

pattern GL_GEOMETRY_TEXTURE = 0x829E

pattern GL_GET_TEXTURE_IMAGE_FORMAT = 0x8291

pattern GL_GET_TEXTURE_IMAGE_TYPE = 0x8292

pattern GL_IMAGE_CLASS_10_10_10_2 = 0x82C3

pattern GL_IMAGE_CLASS_11_11_10 = 0x82C2

pattern GL_IMAGE_CLASS_1_X_16 = 0x82BE

pattern GL_IMAGE_CLASS_1_X_32 = 0x82BB

pattern GL_IMAGE_CLASS_1_X_8 = 0x82C1

pattern GL_IMAGE_CLASS_2_X_16 = 0x82BD

pattern GL_IMAGE_CLASS_2_X_32 = 0x82BA

pattern GL_IMAGE_CLASS_2_X_8 = 0x82C0

pattern GL_IMAGE_CLASS_4_X_16 = 0x82BC

pattern GL_IMAGE_CLASS_4_X_32 = 0x82B9

pattern GL_IMAGE_CLASS_4_X_8 = 0x82BF

pattern GL_IMAGE_COMPATIBILITY_CLASS = 0x82A8

pattern GL_IMAGE_PIXEL_FORMAT = 0x82A9

pattern GL_IMAGE_PIXEL_TYPE = 0x82AA

pattern GL_IMAGE_TEXEL_SIZE = 0x82A7

pattern GL_INTERNALFORMAT_ALPHA_SIZE = 0x8274

pattern GL_INTERNALFORMAT_ALPHA_TYPE = 0x827B

pattern GL_INTERNALFORMAT_BLUE_SIZE = 0x8273

pattern GL_INTERNALFORMAT_BLUE_TYPE = 0x827A

pattern GL_INTERNALFORMAT_DEPTH_SIZE = 0x8275

pattern GL_INTERNALFORMAT_DEPTH_TYPE = 0x827C

pattern GL_INTERNALFORMAT_GREEN_SIZE = 0x8272

pattern GL_INTERNALFORMAT_GREEN_TYPE = 0x8279

pattern GL_INTERNALFORMAT_PREFERRED = 0x8270

pattern GL_INTERNALFORMAT_RED_SIZE = 0x8271

pattern GL_INTERNALFORMAT_RED_TYPE = 0x8278

pattern GL_INTERNALFORMAT_SHARED_SIZE = 0x8277

pattern GL_INTERNALFORMAT_STENCIL_SIZE = 0x8276

pattern GL_INTERNALFORMAT_STENCIL_TYPE = 0x827D

pattern GL_INTERNALFORMAT_SUPPORTED = 0x826F

pattern GL_IS_PER_PATCH = 0x92E7

pattern GL_IS_ROW_MAJOR = 0x9300

pattern GL_LOCATION = 0x930E

pattern GL_LOCATION_INDEX = 0x930F

pattern GL_MANUAL_GENERATE_MIPMAP = 0x8294

pattern GL_MATRIX_STRIDE = 0x92FF

pattern GL_MAX_COMBINED_COMPUTE_UNIFORM_COMPONENTS = 0x8266

pattern GL_MAX_COMBINED_DIMENSIONS = 0x8282

pattern GL_MAX_COMBINED_SHADER_OUTPUT_RESOURCES = 0x8F39

pattern GL_MAX_COMBINED_SHADER_STORAGE_BLOCKS = 0x90DC

pattern GL_MAX_COMPUTE_ATOMIC_COUNTERS = 0x8265

pattern GL_MAX_COMPUTE_ATOMIC_COUNTER_BUFFERS = 0x8264

pattern GL_MAX_COMPUTE_IMAGE_UNIFORMS = 0x91BD

pattern GL_MAX_COMPUTE_SHADER_STORAGE_BLOCKS = 0x90DB

pattern GL_MAX_COMPUTE_SHARED_MEMORY_SIZE = 0x8262

pattern GL_MAX_COMPUTE_TEXTURE_IMAGE_UNITS = 0x91BC

pattern GL_MAX_COMPUTE_UNIFORM_BLOCKS = 0x91BB

pattern GL_MAX_COMPUTE_UNIFORM_COMPONENTS = 0x8263

pattern GL_MAX_COMPUTE_WORK_GROUP_COUNT = 0x91BE

pattern GL_MAX_COMPUTE_WORK_GROUP_INVOCATIONS = 0x90EB

pattern GL_MAX_COMPUTE_WORK_GROUP_SIZE = 0x91BF

pattern GL_MAX_DEBUG_GROUP_STACK_DEPTH = 0x826C

pattern GL_MAX_DEBUG_LOGGED_MESSAGES = 0x9144

pattern GL_MAX_DEBUG_MESSAGE_LENGTH = 0x9143

pattern GL_MAX_DEPTH = 0x8280

pattern GL_MAX_ELEMENT_INDEX = 0x8D6B

pattern GL_MAX_FRAGMENT_SHADER_STORAGE_BLOCKS = 0x90DA

pattern GL_MAX_FRAMEBUFFER_HEIGHT = 0x9316

pattern GL_MAX_FRAMEBUFFER_LAYERS = 0x9317

pattern GL_MAX_FRAMEBUFFER_SAMPLES = 0x9318

pattern GL_MAX_FRAMEBUFFER_WIDTH = 0x9315

pattern GL_MAX_GEOMETRY_SHADER_STORAGE_BLOCKS = 0x90D7

pattern GL_MAX_HEIGHT = 0x827F

pattern GL_MAX_LABEL_LENGTH = 0x82E8

pattern GL_MAX_LAYERS = 0x8281

pattern GL_MAX_NAME_LENGTH = 0x92F6

pattern GL_MAX_NUM_ACTIVE_VARIABLES = 0x92F7

pattern GL_MAX_NUM_COMPATIBLE_SUBROUTINES = 0x92F8

pattern GL_MAX_SHADER_STORAGE_BLOCK_SIZE = 0x90DE

pattern GL_MAX_SHADER_STORAGE_BUFFER_BINDINGS = 0x90DD

pattern GL_MAX_TESS_CONTROL_SHADER_STORAGE_BLOCKS = 0x90D8

pattern GL_MAX_TESS_EVALUATION_SHADER_STORAGE_BLOCKS = 0x90D9

pattern GL_MAX_UNIFORM_LOCATIONS = 0x826E

pattern GL_MAX_VERTEX_ATTRIB_BINDINGS = 0x82DA

pattern GL_MAX_VERTEX_ATTRIB_RELATIVE_OFFSET = 0x82D9

pattern GL_MAX_VERTEX_SHADER_STORAGE_BLOCKS = 0x90D6

pattern GL_MAX_WIDTH = 0x827E

pattern GL_MIPMAP = 0x8293

pattern GL_NAME_LENGTH = 0x92F9

pattern GL_NUM_ACTIVE_VARIABLES = 0x9304

pattern GL_OFFSET = 0x92FC

pattern GL_PRIMITIVE_RESTART_FIXED_INDEX = 0x8D69

pattern GL_PROGRAM = 0x82E2

pattern GL_PROGRAM_INPUT = 0x92E3

pattern GL_PROGRAM_OUTPUT = 0x92E4

pattern GL_PROGRAM_PIPELINE = 0x82E4

pattern GL_QUERY = 0x82E3

pattern GL_READ_PIXELS = 0x828C

pattern GL_READ_PIXELS_FORMAT = 0x828D

pattern GL_READ_PIXELS_TYPE = 0x828E

pattern GL_REFERENCED_BY_COMPUTE_SHADER = 0x930B

pattern GL_REFERENCED_BY_FRAGMENT_SHADER = 0x930A

pattern GL_REFERENCED_BY_GEOMETRY_SHADER = 0x9309

pattern GL_REFERENCED_BY_TESS_CONTROL_SHADER = 0x9307

pattern GL_REFERENCED_BY_TESS_EVALUATION_SHADER = 0x9308

pattern GL_REFERENCED_BY_VERTEX_SHADER = 0x9306

pattern GL_SAMPLER = 0x82E6

pattern GL_SHADER = 0x82E1

pattern GL_SHADER_IMAGE_ATOMIC = 0x82A6

pattern GL_SHADER_IMAGE_LOAD = 0x82A4

pattern GL_SHADER_IMAGE_STORE = 0x82A5

pattern GL_SHADER_STORAGE_BARRIER_BIT = 0x00002000

pattern GL_SHADER_STORAGE_BLOCK = 0x92E6

pattern GL_SHADER_STORAGE_BUFFER = 0x90D2

pattern GL_SHADER_STORAGE_BUFFER_BINDING = 0x90D3

pattern GL_SHADER_STORAGE_BUFFER_OFFSET_ALIGNMENT = 0x90DF

pattern GL_SHADER_STORAGE_BUFFER_SIZE = 0x90D5

pattern GL_SHADER_STORAGE_BUFFER_START = 0x90D4

pattern GL_SIMULTANEOUS_TEXTURE_AND_DEPTH_TEST = 0x82AC

pattern GL_SIMULTANEOUS_TEXTURE_AND_DEPTH_WRITE = 0x82AE

pattern GL_SIMULTANEOUS_TEXTURE_AND_STENCIL_TEST = 0x82AD

pattern GL_SIMULTANEOUS_TEXTURE_AND_STENCIL_WRITE = 0x82AF

pattern GL_SRGB_READ = 0x8297

pattern GL_SRGB_WRITE = 0x8298

pattern GL_STENCIL_COMPONENTS = 0x8285

pattern GL_STENCIL_RENDERABLE = 0x8288

pattern GL_TESS_CONTROL_SUBROUTINE = 0x92E9

pattern GL_TESS_CONTROL_SUBROUTINE_UNIFORM = 0x92EF

pattern GL_TESS_CONTROL_TEXTURE = 0x829C

pattern GL_TESS_EVALUATION_SUBROUTINE = 0x92EA

pattern GL_TESS_EVALUATION_SUBROUTINE_UNIFORM = 0x92F0

pattern GL_TESS_EVALUATION_TEXTURE = 0x829D

pattern GL_TEXTURE_BUFFER_OFFSET = 0x919D

pattern GL_TEXTURE_BUFFER_OFFSET_ALIGNMENT = 0x919F

pattern GL_TEXTURE_BUFFER_SIZE = 0x919E

pattern GL_TEXTURE_COMPRESSED_BLOCK_HEIGHT = 0x82B2

pattern GL_TEXTURE_COMPRESSED_BLOCK_SIZE = 0x82B3

pattern GL_TEXTURE_COMPRESSED_BLOCK_WIDTH = 0x82B1

pattern GL_TEXTURE_GATHER = 0x82A2

pattern GL_TEXTURE_GATHER_SHADOW = 0x82A3

pattern GL_TEXTURE_IMAGE_FORMAT = 0x828F

pattern GL_TEXTURE_IMAGE_TYPE = 0x8290

pattern GL_TEXTURE_IMMUTABLE_LEVELS = 0x82DF

pattern GL_TEXTURE_SHADOW = 0x82A1

pattern GL_TEXTURE_VIEW = 0x82B5

pattern GL_TEXTURE_VIEW_MIN_LAYER = 0x82DD

pattern GL_TEXTURE_VIEW_MIN_LEVEL = 0x82DB

pattern GL_TEXTURE_VIEW_NUM_LAYERS = 0x82DE

pattern GL_TEXTURE_VIEW_NUM_LEVELS = 0x82DC

pattern GL_TOP_LEVEL_ARRAY_SIZE = 0x930C

pattern GL_TOP_LEVEL_ARRAY_STRIDE = 0x930D

pattern GL_TRANSFORM_FEEDBACK_VARYING = 0x92F4

pattern GL_TYPE = 0x92FA

pattern GL_UNIFORM = 0x92E1

pattern GL_UNIFORM_BLOCK = 0x92E2

pattern GL_UNIFORM_BLOCK_REFERENCED_BY_COMPUTE_SHADER = 0x90EC

pattern GL_VERTEX_ATTRIB_BINDING = 0x82D4

pattern GL_VERTEX_ATTRIB_RELATIVE_OFFSET = 0x82D5

pattern GL_VERTEX_BINDING_BUFFER = 0x8F4F

pattern GL_VERTEX_BINDING_DIVISOR = 0x82D6

pattern GL_VERTEX_BINDING_OFFSET = 0x82D7

pattern GL_VERTEX_BINDING_STRIDE = 0x82D8

pattern GL_VERTEX_SUBROUTINE = 0x92E8

pattern GL_VERTEX_SUBROUTINE_UNIFORM = 0x92EE

pattern GL_VERTEX_TEXTURE = 0x829B

pattern GL_VIEW_CLASS_128_BITS = 0x82C4

pattern GL_VIEW_CLASS_16_BITS = 0x82CA

pattern GL_VIEW_CLASS_24_BITS = 0x82C9

pattern GL_VIEW_CLASS_32_BITS = 0x82C8

pattern GL_VIEW_CLASS_48_BITS = 0x82C7

pattern GL_VIEW_CLASS_64_BITS = 0x82C6

pattern GL_VIEW_CLASS_8_BITS = 0x82CB

pattern GL_VIEW_CLASS_96_BITS = 0x82C5

pattern GL_VIEW_CLASS_BPTC_FLOAT = 0x82D3

pattern GL_VIEW_CLASS_BPTC_UNORM = 0x82D2

pattern GL_VIEW_CLASS_RGTC1_RED = 0x82D0

pattern GL_VIEW_CLASS_RGTC2_RG = 0x82D1

pattern GL_VIEW_CLASS_S3TC_DXT1_RGB = 0x82CC

pattern GL_VIEW_CLASS_S3TC_DXT1_RGBA = 0x82CD

pattern GL_VIEW_CLASS_S3TC_DXT3_RGBA = 0x82CE

pattern GL_VIEW_CLASS_S3TC_DXT5_RGBA = 0x82CF

pattern GL_VIEW_COMPATIBILITY_CLASS = 0x82B6

pattern GL_BUFFER_IMMUTABLE_STORAGE = 0x821F

pattern GL_BUFFER_STORAGE_FLAGS = 0x8220

pattern GL_CLEAR_TEXTURE = 0x9365

pattern GL_CLIENT_MAPPED_BUFFER_BARRIER_BIT = 0x00004000

pattern GL_CLIENT_STORAGE_BIT = 0x0200

pattern GL_DYNAMIC_STORAGE_BIT = 0x0100

pattern GL_LOCATION_COMPONENT = 0x934A

pattern GL_MAP_COHERENT_BIT = 0x0080

pattern GL_MAP_PERSISTENT_BIT = 0x0040

pattern GL_MAX_VERTEX_ATTRIB_STRIDE = 0x82E5

pattern GL_MIRROR_CLAMP_TO_EDGE = 0x8743

pattern GL_PRIMITIVE_RESTART_FOR_PATCHES_SUPPORTED = 0x8221

pattern GL_QUERY_BUFFER = 0x9192

pattern GL_QUERY_BUFFER_BARRIER_BIT = 0x00008000

pattern GL_QUERY_BUFFER_BINDING = 0x9193

pattern GL_QUERY_RESULT_NO_WAIT = 0x9194

pattern GL_TEXTURE_BUFFER_BINDING = 0x8C2A

pattern GL_TRANSFORM_FEEDBACK_BUFFER_INDEX = 0x934B

pattern GL_TRANSFORM_FEEDBACK_BUFFER_STRIDE = 0x934C

pattern GL_CLIP_DEPTH_MODE = 0x935D

pattern GL_CLIP_ORIGIN = 0x935C

pattern GL_CONTEXT_FLAG_ROBUST_ACCESS_BIT = 0x00000004

pattern GL_CONTEXT_LOST = 0x0507

pattern GL_CONTEXT_RELEASE_BEHAVIOR = 0x82FB

pattern GL_CONTEXT_RELEASE_BEHAVIOR_FLUSH = 0x82FC

pattern GL_GUILTY_CONTEXT_RESET = 0x8253

pattern GL_INNOCENT_CONTEXT_RESET = 0x8254

pattern GL_LOSE_CONTEXT_ON_RESET = 0x8252

pattern GL_MAX_COMBINED_CLIP_AND_CULL_DISTANCES = 0x82FA

pattern GL_MAX_CULL_DISTANCES = 0x82F9

pattern GL_NEGATIVE_ONE_TO_ONE = 0x935E

pattern GL_NO_RESET_NOTIFICATION = 0x8261

pattern GL_QUERY_BY_REGION_NO_WAIT_INVERTED = 0x8E1A

pattern GL_QUERY_BY_REGION_WAIT_INVERTED = 0x8E19

pattern GL_QUERY_NO_WAIT_INVERTED = 0x8E18

pattern GL_QUERY_TARGET = 0x82EA

pattern GL_QUERY_WAIT_INVERTED = 0x8E17

pattern GL_RESET_NOTIFICATION_STRATEGY = 0x8256

pattern GL_TEXTURE_TARGET = 0x1006

pattern GL_UNKNOWN_CONTEXT_RESET = 0x8255

pattern GL_ZERO_TO_ONE = 0x935F

pattern GL_BLEND_EQUATION = 0x8009

pattern GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS = 0x8CD9

pattern GL_SUBSAMPLE_DISTANCE_AMD = 0x883F

pattern GL_FLOAT16_NV = 0x8FF8

pattern GL_FLOAT16_VEC2_NV = 0x8FF9

pattern GL_FLOAT16_VEC3_NV = 0x8FFA

pattern GL_FLOAT16_VEC4_NV = 0x8FFB

pattern GL_INT16_NV = 0x8FE4

pattern GL_INT16_VEC2_NV = 0x8FE5

pattern GL_INT16_VEC3_NV = 0x8FE6

pattern GL_INT16_VEC4_NV = 0x8FE7

pattern GL_INT64_NV = 0x140E

pattern GL_INT64_VEC2_NV = 0x8FE9

pattern GL_INT64_VEC3_NV = 0x8FEA

pattern GL_INT64_VEC4_NV = 0x8FEB

pattern GL_INT8_NV = 0x8FE0

pattern GL_INT8_VEC2_NV = 0x8FE1

pattern GL_INT8_VEC3_NV = 0x8FE2

pattern GL_INT8_VEC4_NV = 0x8FE3

pattern GL_UNSIGNED_INT16_NV = 0x8FF0

pattern GL_UNSIGNED_INT16_VEC2_NV = 0x8FF1

pattern GL_UNSIGNED_INT16_VEC3_NV = 0x8FF2

pattern GL_UNSIGNED_INT16_VEC4_NV = 0x8FF3

pattern GL_UNSIGNED_INT64_NV = 0x140F

pattern GL_UNSIGNED_INT64_VEC2_NV = 0x8FF5

pattern GL_UNSIGNED_INT64_VEC3_NV = 0x8FF6

pattern GL_UNSIGNED_INT64_VEC4_NV = 0x8FF7

pattern GL_UNSIGNED_INT8_NV = 0x8FEC

pattern GL_UNSIGNED_INT8_VEC2_NV = 0x8FED

pattern GL_UNSIGNED_INT8_VEC3_NV = 0x8FEE

pattern GL_UNSIGNED_INT8_VEC4_NV = 0x8FEF

pattern GL_DEPTH24_STENCIL8_OES = 0x88F0

pattern GL_DEPTH_COMPONENT32_OES = 0x81A7

pattern GL_DEPTH_STENCIL_OES = 0x84F9

pattern GL_UNSIGNED_INT_24_8_OES = 0x84FA

pattern GL_UNSIGNED_SHORT_8_8_APPLE = 0x85BA

pattern GL_UNSIGNED_SHORT_8_8_REV_APPLE = 0x85BB

pattern GL_BGRA8_EXT = 0x93A1

pattern GL_BGRA_EXT = 0x80E1

pattern GL_STORAGE_CACHED_APPLE = 0x85BE

pattern GL_STORAGE_SHARED_APPLE = 0x85BF

pattern GL_UNSIGNED_INT64_ARB = 0x140F

pattern GL_CURRENT_MATRIX_ARB = 0x8641

pattern GL_CURRENT_MATRIX_STACK_DEPTH_ARB = 0x8640

pattern GL_MATRIX0_ARB = 0x88C0

pattern GL_MATRIX10_ARB = 0x88CA

pattern GL_MATRIX11_ARB = 0x88CB

pattern GL_MATRIX12_ARB = 0x88CC

pattern GL_MATRIX13_ARB = 0x88CD

pattern GL_MATRIX14_ARB = 0x88CE

pattern GL_MATRIX15_ARB = 0x88CF

pattern GL_MATRIX16_ARB = 0x88D0

pattern GL_MATRIX17_ARB = 0x88D1

pattern GL_MATRIX18_ARB = 0x88D2

pattern GL_MATRIX19_ARB = 0x88D3

pattern GL_MATRIX1_ARB = 0x88C1

pattern GL_MATRIX20_ARB = 0x88D4

pattern GL_MATRIX21_ARB = 0x88D5

pattern GL_MATRIX22_ARB = 0x88D6

pattern GL_MATRIX23_ARB = 0x88D7

pattern GL_MATRIX24_ARB = 0x88D8

pattern GL_MATRIX25_ARB = 0x88D9

pattern GL_MATRIX26_ARB = 0x88DA

pattern GL_MATRIX27_ARB = 0x88DB

pattern GL_MATRIX28_ARB = 0x88DC

pattern GL_MATRIX29_ARB = 0x88DD

pattern GL_MATRIX2_ARB = 0x88C2

pattern GL_MATRIX30_ARB = 0x88DE

pattern GL_MATRIX31_ARB = 0x88DF

pattern GL_MATRIX3_ARB = 0x88C3

pattern GL_MATRIX4_ARB = 0x88C4

pattern GL_MATRIX5_ARB = 0x88C5

pattern GL_MATRIX6_ARB = 0x88C6

pattern GL_MATRIX7_ARB = 0x88C7

pattern GL_MATRIX8_ARB = 0x88C8

pattern GL_MATRIX9_ARB = 0x88C9

pattern GL_MAX_PROGRAM_ATTRIBS_ARB = 0x88AD

pattern GL_MAX_PROGRAM_ENV_PARAMETERS_ARB = 0x88B5

pattern GL_MAX_PROGRAM_INSTRUCTIONS_ARB = 0x88A1

pattern GL_MAX_PROGRAM_LOCAL_PARAMETERS_ARB = 0x88B4

pattern GL_MAX_PROGRAM_MATRICES_ARB = 0x862F

pattern GL_MAX_PROGRAM_MATRIX_STACK_DEPTH_ARB = 0x862E

pattern GL_MAX_PROGRAM_NATIVE_ATTRIBS_ARB = 0x88AF

pattern GL_MAX_PROGRAM_NATIVE_INSTRUCTIONS_ARB = 0x88A3

pattern GL_MAX_PROGRAM_NATIVE_PARAMETERS_ARB = 0x88AB

pattern GL_MAX_PROGRAM_NATIVE_TEMPORARIES_ARB = 0x88A7

pattern GL_MAX_PROGRAM_PARAMETERS_ARB = 0x88A9

pattern GL_MAX_PROGRAM_TEMPORARIES_ARB = 0x88A5

pattern GL_MAX_TEXTURE_COORDS_ARB = 0x8871

pattern GL_MAX_TEXTURE_IMAGE_UNITS_ARB = 0x8872

pattern GL_PROGRAM_ATTRIBS_ARB = 0x88AC

pattern GL_PROGRAM_BINDING_ARB = 0x8677

pattern GL_PROGRAM_ERROR_POSITION_ARB = 0x864B

pattern GL_PROGRAM_ERROR_STRING_ARB = 0x8874

pattern GL_PROGRAM_FORMAT_ARB = 0x8876

pattern GL_PROGRAM_FORMAT_ASCII_ARB = 0x8875

pattern GL_PROGRAM_INSTRUCTIONS_ARB = 0x88A0

pattern GL_PROGRAM_LENGTH_ARB = 0x8627

pattern GL_PROGRAM_NATIVE_ATTRIBS_ARB = 0x88AE

pattern GL_PROGRAM_NATIVE_INSTRUCTIONS_ARB = 0x88A2

pattern GL_PROGRAM_NATIVE_PARAMETERS_ARB = 0x88AA

pattern GL_PROGRAM_NATIVE_TEMPORARIES_ARB = 0x88A6

pattern GL_PROGRAM_PARAMETERS_ARB = 0x88A8

pattern GL_PROGRAM_STRING_ARB = 0x8628

pattern GL_PROGRAM_TEMPORARIES_ARB = 0x88A4

pattern GL_PROGRAM_UNDER_NATIVE_LIMITS_ARB = 0x88B6

pattern GL_TRANSPOSE_CURRENT_MATRIX_ARB = 0x88B7

pattern GL_SAMPLES_ARB = 0x80A9

pattern GL_TEXTURE0_ARB = 0x84C0

pattern GL_TEXTURE1_ARB = 0x84C1

pattern GL_FLOAT_MAT2_ARB = 0x8B5A

pattern GL_FLOAT_MAT3_ARB = 0x8B5B

pattern GL_FLOAT_MAT4_ARB = 0x8B5C

pattern GL_FLOAT_VEC2_ARB = 0x8B50

pattern GL_FLOAT_VEC3_ARB = 0x8B51

pattern GL_FLOAT_VEC4_ARB = 0x8B52

pattern GL_CURRENT_VERTEX_ATTRIB_ARB = 0x8626

pattern GL_MAX_VERTEX_ATTRIBS_ARB = 0x8869

pattern GL_VERTEX_ATTRIB_ARRAY_ENABLED_ARB = 0x8622

pattern GL_VERTEX_ATTRIB_ARRAY_NORMALIZED_ARB = 0x886A

pattern GL_VERTEX_ATTRIB_ARRAY_POINTER_ARB = 0x8645

pattern GL_VERTEX_ATTRIB_ARRAY_SIZE_ARB = 0x8623

pattern GL_VERTEX_ATTRIB_ARRAY_STRIDE_ARB = 0x8624

pattern GL_VERTEX_ATTRIB_ARRAY_TYPE_ARB = 0x8625

pattern GL_VERTEX_PROGRAM_POINT_SIZE_ARB = 0x8642

pattern GL_VERTEX_PROGRAM_TWO_SIDE_ARB = 0x8643

pattern GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS_ARB = 0x8B4C

pattern GL_CURRENT_QUERY_EXT = 0x8865

pattern GL_QUERY_RESULT_AVAILABLE_EXT = 0x8867

pattern GL_QUERY_RESULT_EXT = 0x8866

pattern GL_TIME_ELAPSED_EXT = 0x88BF

pattern GL_COLOR_ATTACHMENT0_EXT = 0x8CE0

pattern GL_COLOR_ATTACHMENT10_EXT = 0x8CEA

pattern GL_COLOR_ATTACHMENT11_EXT = 0x8CEB

pattern GL_COLOR_ATTACHMENT12_EXT = 0x8CEC

pattern GL_COLOR_ATTACHMENT13_EXT = 0x8CED

pattern GL_COLOR_ATTACHMENT14_EXT = 0x8CEE

pattern GL_COLOR_ATTACHMENT15_EXT = 0x8CEF

pattern GL_COLOR_ATTACHMENT1_EXT = 0x8CE1

pattern GL_COLOR_ATTACHMENT2_EXT = 0x8CE2

pattern GL_COLOR_ATTACHMENT3_EXT = 0x8CE3

pattern GL_COLOR_ATTACHMENT4_EXT = 0x8CE4

pattern GL_COLOR_ATTACHMENT5_EXT = 0x8CE5

pattern GL_COLOR_ATTACHMENT6_EXT = 0x8CE6

pattern GL_COLOR_ATTACHMENT7_EXT = 0x8CE7

pattern GL_COLOR_ATTACHMENT8_EXT = 0x8CE8

pattern GL_COLOR_ATTACHMENT9_EXT = 0x8CE9

pattern GL_MAX_COLOR_ATTACHMENTS_EXT = 0x8CDF

pattern GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE_EXT = 0x8D56

pattern GL_MAX_SAMPLES_EXT = 0x8D57

pattern GL_RENDERBUFFER_SAMPLES_EXT = 0x8CAB

pattern GL_FRAMEBUFFER_SRGB_EXT = 0x8DB9

pattern GL_FIRST_VERTEX_CONVENTION_EXT = 0x8E4D

pattern GL_FRAMEBUFFER_ATTACHMENT_LAYERED_EXT = 0x8DA7

pattern GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS_EXT = 0x8DA8

pattern GL_GEOMETRY_SHADER_EXT = 0x8DD9

pattern GL_LAST_VERTEX_CONVENTION_EXT = 0x8E4E

pattern GL_LINES_ADJACENCY_EXT = 0x000A

pattern GL_LINE_STRIP_ADJACENCY_EXT = 0x000B

pattern GL_MAX_GEOMETRY_OUTPUT_VERTICES_EXT = 0x8DE0

pattern GL_MAX_GEOMETRY_TEXTURE_IMAGE_UNITS_EXT = 0x8C29

pattern GL_MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS_EXT = 0x8DE1

pattern GL_MAX_GEOMETRY_UNIFORM_COMPONENTS_EXT = 0x8DDF

pattern GL_PRIMITIVES_GENERATED_EXT = 0x8C87

pattern GL_TRIANGLES_ADJACENCY_EXT = 0x000C

pattern GL_TRIANGLE_STRIP_ADJACENCY_EXT = 0x000D

pattern GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER_EXT = 0x8CD4

pattern GL_FRAMEBUFFER_INCOMPLETE_LAYER_COUNT_EXT = 0x8DA9

pattern GL_GEOMETRY_INPUT_TYPE_EXT = 0x8DDB

pattern GL_GEOMETRY_OUTPUT_TYPE_EXT = 0x8DDC

pattern GL_GEOMETRY_VERTICES_OUT_EXT = 0x8DDA

pattern GL_PROGRAM_POINT_SIZE_EXT = 0x8642

pattern GL_INT_SAMPLER_BUFFER_EXT = 0x8DD0

pattern GL_SAMPLER_BUFFER_EXT = 0x8DC2

pattern GL_UNSIGNED_INT_SAMPLER_BUFFER_EXT = 0x8DD8

pattern GL_MULTISAMPLE_EXT = 0x809D

pattern GL_SAMPLE_ALPHA_TO_ONE_EXT = 0x809F

pattern GL_EFFECTIVE_RASTER_SAMPLES_EXT = 0x932C

pattern GL_MAX_RASTER_SAMPLES_EXT = 0x9329

pattern GL_MULTISAMPLE_RASTERIZATION_ALLOWED_EXT = 0x932B

pattern GL_RASTER_FIXED_SAMPLE_LOCATIONS_EXT = 0x932A

pattern GL_RASTER_MULTISAMPLE_EXT = 0x9327

pattern GL_RASTER_SAMPLES_EXT = 0x9328

pattern GL_R16_SNORM_EXT = 0x8F98

pattern GL_RG16_SNORM_EXT = 0x8F99

pattern GL_RGBA16_SNORM_EXT = 0x8F9B

pattern GL_SRGB8_ALPHA8_EXT = 0x8C43

pattern GL_SRGB_ALPHA_EXT = 0x8C42

pattern GL_SRGB_EXT = 0x8C40

pattern GL_IMAGE_BUFFER_EXT = 0x9051

pattern GL_IMAGE_CUBE_MAP_ARRAY_EXT = 0x9054

pattern GL_INT_IMAGE_BUFFER_EXT = 0x905C

pattern GL_INT_IMAGE_CUBE_MAP_ARRAY_EXT = 0x905F

pattern GL_UNSIGNED_INT_IMAGE_BUFFER_EXT = 0x9067

pattern GL_UNSIGNED_INT_IMAGE_CUBE_MAP_ARRAY_EXT = 0x906A

pattern GL_TEXTURE_CUBE_MAP_ARRAY_OES = 0x9009

pattern GL_ALPHA8_EXT = 0x803C

pattern GL_LUMINANCE8_ALPHA8_EXT = 0x8045

pattern GL_LUMINANCE8_EXT = 0x8040

pattern GL_RGB10_A2_EXT = 0x8059

pattern GL_RGB10_EXT = 0x8052

pattern GL_RGB16_EXT = 0x8054

pattern GL_RGBA16_EXT = 0x805B

pattern GL_MAX_TEXTURE_BUFFER_SIZE_EXT = 0x8C2B

pattern GL_TEXTURE_BINDING_BUFFER_EXT = 0x8C2C

pattern GL_TEXTURE_BUFFER_DATA_STORE_BINDING_EXT = 0x8C2D

pattern GL_TEXTURE_BUFFER_EXT = 0x8C2A

pattern GL_COMPRESSED_RGBA_S3TC_DXT1_EXT = 0x83F1

pattern GL_COMPRESSED_RGB_S3TC_DXT1_EXT = 0x83F0

pattern GL_R8_EXT = 0x8229

pattern GL_RG8_EXT = 0x822B

pattern GL_REQUIRED_TEXTURE_IMAGE_UNITS_OES = 0x8D68

pattern GL_TEXTURE_BINDING_EXTERNAL_OES = 0x8D67

pattern GL_TEXTURE_EXTERNAL_OES = 0x8D65

pattern GL_CONTEXT_ROBUST_ACCESS = 0x90F3

pattern GL_COMPRESSED_RGBA_ASTC_10x10_KHR = 0x93BB

pattern GL_COMPRESSED_RGBA_ASTC_10x5_KHR = 0x93B8

pattern GL_COMPRESSED_RGBA_ASTC_10x6_KHR = 0x93B9

pattern GL_COMPRESSED_RGBA_ASTC_10x8_KHR = 0x93BA

pattern GL_COMPRESSED_RGBA_ASTC_12x10_KHR = 0x93BC

pattern GL_COMPRESSED_RGBA_ASTC_12x12_KHR = 0x93BD

pattern GL_COMPRESSED_RGBA_ASTC_4x4_KHR = 0x93B0

pattern GL_COMPRESSED_RGBA_ASTC_5x4_KHR = 0x93B1

pattern GL_COMPRESSED_RGBA_ASTC_5x5_KHR = 0x93B2

pattern GL_COMPRESSED_RGBA_ASTC_6x5_KHR = 0x93B3

pattern GL_COMPRESSED_RGBA_ASTC_6x6_KHR = 0x93B4

pattern GL_COMPRESSED_RGBA_ASTC_8x5_KHR = 0x93B5

pattern GL_COMPRESSED_RGBA_ASTC_8x6_KHR = 0x93B6

pattern GL_COMPRESSED_RGBA_ASTC_8x8_KHR = 0x93B7

pattern GL_COMPRESSED_SRGB8_ALPHA8_ASTC_10x10_KHR = 0x93DB

pattern GL_COMPRESSED_SRGB8_ALPHA8_ASTC_10x5_KHR = 0x93D8

pattern GL_COMPRESSED_SRGB8_ALPHA8_ASTC_10x6_KHR = 0x93D9

pattern GL_COMPRESSED_SRGB8_ALPHA8_ASTC_10x8_KHR = 0x93DA

pattern GL_COMPRESSED_SRGB8_ALPHA8_ASTC_12x10_KHR = 0x93DC

pattern GL_COMPRESSED_SRGB8_ALPHA8_ASTC_12x12_KHR = 0x93DD

pattern GL_COMPRESSED_SRGB8_ALPHA8_ASTC_4x4_KHR = 0x93D0

pattern GL_COMPRESSED_SRGB8_ALPHA8_ASTC_5x4_KHR = 0x93D1

pattern GL_COMPRESSED_SRGB8_ALPHA8_ASTC_5x5_KHR = 0x93D2

pattern GL_COMPRESSED_SRGB8_ALPHA8_ASTC_6x5_KHR = 0x93D3

pattern GL_COMPRESSED_SRGB8_ALPHA8_ASTC_6x6_KHR = 0x93D4

pattern GL_COMPRESSED_SRGB8_ALPHA8_ASTC_8x5_KHR = 0x93D5

pattern GL_COMPRESSED_SRGB8_ALPHA8_ASTC_8x6_KHR = 0x93D6

pattern GL_COMPRESSED_SRGB8_ALPHA8_ASTC_8x8_KHR = 0x93D7

pattern GL_COLOR_ATTACHMENT0_NV = 0x8CE0

pattern GL_COLOR_ATTACHMENT10_NV = 0x8CEA

pattern GL_COLOR_ATTACHMENT11_NV = 0x8CEB

pattern GL_COLOR_ATTACHMENT12_NV = 0x8CEC

pattern GL_COLOR_ATTACHMENT13_NV = 0x8CED

pattern GL_COLOR_ATTACHMENT14_NV = 0x8CEE

pattern GL_COLOR_ATTACHMENT15_NV = 0x8CEF

pattern GL_COLOR_ATTACHMENT1_NV = 0x8CE1

pattern GL_COLOR_ATTACHMENT2_NV = 0x8CE2

pattern GL_COLOR_ATTACHMENT3_NV = 0x8CE3

pattern GL_COLOR_ATTACHMENT4_NV = 0x8CE4

pattern GL_COLOR_ATTACHMENT5_NV = 0x8CE5

pattern GL_COLOR_ATTACHMENT6_NV = 0x8CE6

pattern GL_COLOR_ATTACHMENT7_NV = 0x8CE7

pattern GL_COLOR_ATTACHMENT8_NV = 0x8CE8

pattern GL_COLOR_ATTACHMENT9_NV = 0x8CE9

pattern GL_MAX_PROGRAM_CALL_DEPTH_NV = 0x88F5

pattern GL_MAX_PROGRAM_EXEC_INSTRUCTIONS_NV = 0x88F4

pattern GL_COLOR_SAMPLES_NV = 0x8E20

pattern GL_PRIMARY_COLOR_NV = 0x852C

pattern GL_SECONDARY_COLOR_NV = 0x852D

pattern GL_DEPTH_COMPONENT24_OES = 0x81A6

pattern GL_DEPTH_COMPONENT16_OES = 0x81A5

pattern GL_RGB565_OES = 0x8D62

pattern GL_RGB5_A1_OES = 0x8057

pattern GL_RGBA4_OES = 0x8056

pattern GL_RGB8_OES = 0x8051

pattern GL_RGBA8_OES = 0x8058

pattern GL_STENCIL_INDEX8_OES = 0x8D48

pattern GL_HALF_FLOAT_OES = 0x8D61

pattern GL_CONTEXT_COMPATIBILITY_PROFILE_BIT = 0x00000002

pattern GL_CONTEXT_CORE_PROFILE_BIT = 0x00000001

pattern GL_CONTEXT_PROFILE_MASK = 0x9126

pattern GL_PROGRAM_POINT_SIZE = 0x8642

-- Core 3.2

glClearBufferfv :: MonadIO m => GLenum -> GLint -> Ptr GLfloat -> m ()
glClearBufferfv _ _ _ = liftIO $ putStrLn "glClearBufferfv" >> return ()

glClearBufferuiv :: MonadIO m => GLenum -> GLint -> Ptr GLuint -> m ()
glClearBufferuiv _ _ _ = liftIO $ putStrLn "glClearBufferuiv" >> return ()

glClearBufferiv :: MonadIO m => GLenum -> GLint -> Ptr GLint -> m () 
glClearBufferiv _ _ _ = liftIO $ putStrLn "glClearBufferiv" >> return ()

glTexParameterfv :: MonadIO m => GLenum -> GLenum -> Ptr GLfloat -> m ()
glTexParameterfv _ _ _ = liftIO $ putStrLn "glTexParameterfv" >> return ()

glTexParameterIuiv :: MonadIO m => GLenum -> GLenum -> Ptr GLuint -> m ()
glTexParameterIuiv _ _ _ = liftIO $ putStrLn "glTexParameterIuiv" >> return ()

glTexParameterIiv :: MonadIO m => GLenum -> GLenum -> Ptr GLint -> m ()
glTexParameterIiv _ _ _ = liftIO $ putStrLn "glTexParameterIiv" >> return ()

glPixelStorei :: MonadIO m => GLenum -> GLint -> m () 
glPixelStorei _ _ = liftIO $ putStrLn "glPixelStorei" >> return ()

glEnable :: MonadIO m => GLenum -> m ()
glEnable _ = liftIO $ putStrLn "glEnable" >> return ()

glGetIntegerv :: MonadIO m => GLenum -> Ptr GLint -> m ()
glGetIntegerv _ ptr = liftIO $ do
    poke ptr 100
    putStrLn "glGetIntegerv"

glDeleteProgram :: MonadIO m => GLuint -> m ()
glDeleteProgram _ = liftIO $ putStrLn "glDeleteProgram" >> return ()

glDeleteBuffers :: MonadIO m => GLsizei -> Ptr GLuint -> m ()
glDeleteBuffers _ _ = liftIO $ putStrLn "glDeleteBuffers" >> return ()

nextNameRef :: IORef GLuint
nextNameRef = unsafePerformIO $ newIORef 1

glCreateShader :: MonadIO m => GLenum -> m GLuint
glCreateShader _ = do
    liftIO $ putStrLn "glCreateShader"
    nextName <- liftIO $ readIORef nextNameRef
    liftIO $ writeIORef nextNameRef (nextName + 1)
    return nextName

glCreateProgram :: MonadIO m => m GLuint
glCreateProgram = do
    liftIO $ putStrLn "glCreateProgram"
    nextName <- liftIO $ readIORef nextNameRef
    liftIO $ writeIORef nextNameRef (nextName + 1)
    return nextName

glAttachShader :: MonadIO m => GLuint -> GLuint -> m ()
glAttachShader _ _ = liftIO $ putStrLn "glAttachShader" >> return ()

glBindAttribLocation :: MonadIO m => GLuint -> GLuint -> Ptr GLchar -> m ()
glBindAttribLocation _ _ _ = liftIO $ putStrLn "glBindAttribLocation" >> return ()

glDetachShader :: MonadIO m => GLuint -> GLuint -> m ()
glDetachShader _ _ = liftIO $ putStrLn "glDetachShader" >> return ()

glDeleteShader :: MonadIO m => GLuint -> m ()
glDeleteShader _ = liftIO $ putStrLn "glDeleteShader" >> return ()

glGetUniformBlockIndex :: MonadIO m => GLuint -> Ptr GLchar -> m GLuint
glGetUniformBlockIndex _ _ = liftIO $ putStrLn "glGetUniformBlockIndex" >> return 1 -- TODO

glUniformBlockBinding :: MonadIO m => GLuint -> GLuint -> GLuint -> m () 
glUniformBlockBinding _ _ _ = liftIO $ putStrLn "glUniformBlockBinding" >> return ()

glUseProgram :: MonadIO m => GLuint -> m ()
glUseProgram _ = liftIO $ putStrLn "glUseProgram" >> return ()

glGetUniformLocation :: MonadIO m => GLuint -> Ptr GLchar -> m GLint
glGetUniformLocation _ _ = liftIO $ putStrLn "glGetUniformLocation" >> return 1 -- TODO

glUniform1i :: MonadIO m => GLint -> GLint -> m ()
glUniform1i _ _ = liftIO $ putStrLn "glUniform1i" >> return ()

glBindFramebuffer :: MonadIO m => GLenum -> GLuint -> m ()
glBindFramebuffer _ _ = liftIO $ putStrLn "glBindFramebuffer" >> return ()

glGenFramebuffers :: MonadIO m => GLsizei -> Ptr GLuint -> m ()
glGenFramebuffers _ _ = liftIO $ putStrLn "glGenFramebuffers" >> return ()

glDeleteFramebuffers :: MonadIO m => GLsizei -> Ptr GLuint -> m ()
glDeleteFramebuffers _ _ = liftIO $ putStrLn "glDeleteFramebuffers" >> return ()

glDrawBuffers :: MonadIO m => GLsizei -> Ptr GLenum -> m ()
glDrawBuffers _ _ = liftIO $ putStrLn "glDrawBuffers" >> return ()

glBindVertexArray :: MonadIO m => GLuint -> m () 
glBindVertexArray _ = liftIO $ putStrLn "glBindVertexArray" >> return ()

glGenVertexArrays :: MonadIO m => GLsizei -> Ptr GLuint -> m ()
glGenVertexArrays _ _ = liftIO $ putStrLn "glGenVertexArrays" >> return ()

glDeleteVertexArrays :: MonadIO m => GLsizei -> Ptr GLuint -> m ()
glDeleteVertexArrays _ _ = liftIO $ putStrLn "glDeleteVertexArrays" >> return ()

glShaderSource :: MonadIO m => GLuint -> GLsizei -> Ptr (Ptr GLchar) -> Ptr GLint -> m ()
glShaderSource _ _ _ _ = liftIO $ putStrLn "glShaderSource" >> return ()

glCompileShader :: MonadIO m => GLuint -> m ()
glCompileShader _ = liftIO $ putStrLn "glCompileShader" >> return ()

glGetShaderiv :: MonadIO m => GLuint -> GLenum -> Ptr GLint -> m ()
glGetShaderiv _ _ _ = liftIO $ putStrLn "glGetShaderiv" >> return ()

glGetShaderInfoLog :: MonadIO m => GLuint -> GLsizei -> Ptr GLsizei -> Ptr GLchar -> m ()
glGetShaderInfoLog _ _ _ _ = liftIO $ putStrLn "glGetShaderInfoLog" >> return ()

glLinkProgram :: MonadIO m => GLuint -> m ()
glLinkProgram _ = liftIO $ putStrLn "glLinkProgram" >> return ()

glGetProgramiv :: MonadIO m => GLuint -> GLenum -> Ptr GLint -> m ()
glGetProgramiv _ _ _ = liftIO $ putStrLn "glGetProgramiv" >> return ()

glGetProgramInfoLog :: MonadIO m => GLuint -> GLsizei -> Ptr GLsizei -> Ptr GLchar -> m ()
glGetProgramInfoLog _ _ _ _ = liftIO $ putStrLn "glGetProgramInfoLog" >> return ()

glGenBuffers :: MonadIO m => GLsizei -> Ptr GLuint -> m ()
glGenBuffers _ _ = liftIO $ putStrLn "glGenBuffers" >> return ()

glBindBuffer :: MonadIO m => GLenum -> GLuint -> m ()
glBindBuffer _ _ = liftIO $ putStrLn "glBindBuffer" >> return ()

glBufferData :: MonadIO m => GLenum -> GLsizeiptr -> Ptr () -> GLenum -> m ()
glBufferData _ _ _ _ = liftIO $ putStrLn "glBufferData" >> return ()

glBindBufferRange :: MonadIO m => GLenum -> GLuint -> GLuint -> GLintptr -> GLsizeiptr -> m ()
glBindBufferRange _ _ _ _ _ = liftIO $ putStrLn "glBindBufferRange" >> return ()

glCheckFramebufferStatus :: MonadIO m => GLenum -> m GLenum
glCheckFramebufferStatus _ = liftIO $ putStrLn "glCheckFramebufferStatus" >> return GL_FRAMEBUFFER_COMPLETE

glMapBufferRange :: MonadIO m => GLenum -> GLintptr -> GLsizeiptr -> GLbitfield -> m (Ptr ())
glMapBufferRange _ _ _ _ = liftIO $ putStrLn "glMapBufferRange" >> return nullPtr

glFlushMappedBufferRange :: MonadIO m => GLenum -> GLintptr -> GLsizeiptr -> m ()
glFlushMappedBufferRange _ _ _ = liftIO $ putStrLn "glFlushMappedBufferRange" >> return ()

glUnmapBuffer :: MonadIO m => GLenum -> m GLboolean
glUnmapBuffer _ = liftIO $ putStrLn "glUnmapBuffer" >> return 1

glCopyBufferSubData :: MonadIO m => GLenum -> GLenum -> GLintptr -> GLintptr -> GLsizeiptr -> m ()
glCopyBufferSubData _ _ _ _ _ = liftIO $ putStrLn "glCopyBufferSubData" >> return ()

glDrawArrays :: MonadIO m => GLenum -> GLint -> GLsizei -> m ()
glDrawArrays _ _ _ = liftIO $ putStrLn "glDrawArrays" >> return ()

glDrawElementsBaseVertex :: MonadIO m => GLenum -> GLsizei -> GLenum -> Ptr () -> GLint -> m ()
glDrawElementsBaseVertex _ _ _ _ _ = liftIO $ putStrLn "glDrawElementsBaseVertex" >> return ()

glDrawArraysInstanced :: MonadIO m => GLenum -> GLint -> GLsizei -> GLsizei -> m ()
glDrawArraysInstanced _ _ _ _ = liftIO $ putStrLn "glDrawArraysInstanced" >> return ()

glDrawElementsInstancedBaseVertex :: MonadIO m => GLenum -> GLsizei -> GLenum -> Ptr () -> GLsizei -> GLint -> m ()
glDrawElementsInstancedBaseVertex _ _ _ _ _ _ = liftIO $ putStrLn "glDrawElementsInstancedBaseVertex" >> return ()

glPrimitiveRestartIndex :: MonadIO m => GLuint -> m ()
glPrimitiveRestartIndex _ = liftIO $ putStrLn "glPrimitiveRestartIndex" >> return ()

glDisable :: MonadIO m => GLenum -> m ()
glDisable _ = liftIO $ putStrLn "glDisable" >> return ()

glEnableVertexAttribArray :: MonadIO m => GLuint -> m ()
glEnableVertexAttribArray _ = liftIO $ putStrLn "glEnableVertexAttribArray" >> return ()

glVertexAttribPointer :: MonadIO m => GLuint -> GLint -> GLenum -> GLboolean -> GLsizei -> Ptr () -> m ()
glVertexAttribPointer _ _ _ _ _ _ = liftIO $ putStrLn "glVertexAttribPointer" >> return ()

glVertexAttribIPointer :: MonadIO m => GLuint -> GLint -> GLenum -> GLsizei -> Ptr () -> m ()
glVertexAttribIPointer _ _ _ _ _ = liftIO $ putStrLn "glVertexAttribIPointer" >> return ()

glTexImage1D :: MonadIO m => GLenum -> GLint -> GLint -> GLsizei -> GLint -> GLenum -> GLenum -> Ptr () -> m ()
glTexImage1D _ _ _ _ _ _ _ _ = liftIO $ putStrLn "glTexImage1D" >> return ()

glTexImage2D :: MonadIO m => GLenum -> GLint -> GLint -> GLsizei -> GLsizei -> GLint -> GLenum -> GLenum -> Ptr () -> m ()
glTexImage2D _ _ _ _ _ _ _ _ _ = liftIO $ putStrLn "glTexImage2D" >> return ()

glRenderbufferStorage :: MonadIO m => GLenum -> GLenum -> GLsizei -> GLsizei -> m ()
glRenderbufferStorage _ _ _ _ = liftIO $ putStrLn "glRenderbufferStorage" >> return ()

glTexImage3D :: MonadIO m => GLenum -> GLint -> GLint -> GLsizei -> GLsizei -> GLsizei -> GLint -> GLenum -> GLenum -> Ptr () -> m ()
glTexImage3D _ _ _ _ _ _ _ _ _ _ = liftIO $ putStrLn "glTexImage3D" >> return ()

glTexParameteri :: MonadIO m => GLenum -> GLenum -> GLint -> m ()
glTexParameteri _ _ _ = liftIO $ putStrLn "glTexParameteri" >> return ()

glGenTextures :: MonadIO m => GLsizei -> Ptr GLuint -> m ()
glGenTextures _ _ = liftIO $ putStrLn "glGenTextures" >> return ()

glDeleteTextures :: MonadIO m => GLsizei -> Ptr GLuint -> m ()
glDeleteTextures _ _ = liftIO $ putStrLn "glDeleteTextures" >> return ()

glGenRenderbuffers :: MonadIO m => GLsizei -> Ptr GLuint -> m ()
glGenRenderbuffers _ _ = liftIO $ putStrLn "glGenRenderbuffers" >> return ()

glDeleteRenderbuffers :: MonadIO m => GLsizei -> Ptr GLuint -> m ()
glDeleteRenderbuffers _ _ = liftIO $ putStrLn "glDeleteRenderbuffers" >> return ()

glActiveTexture :: MonadIO m => GLenum -> m ()
glActiveTexture _ = liftIO $ putStrLn "glActiveTexture" >> return ()

glBindTexture :: MonadIO m => GLenum -> GLuint -> m ()
glBindTexture _ _ = liftIO $ putStrLn "glBindTexture" >> return ()

glTexSubImage1D :: MonadIO m => GLenum -> GLint -> GLint -> GLsizei -> GLenum -> GLenum -> Ptr () -> m ()
glTexSubImage1D _ _ _ _ _ _ _ = liftIO $ putStrLn "glTexSubImage1D" >> return ()

glTexSubImage2D :: MonadIO m => GLenum -> GLint -> GLint -> GLint -> GLsizei -> GLsizei -> GLenum -> GLenum -> Ptr () -> m ()
glTexSubImage2D _ _ _ _ _ _ _ _ _ = liftIO $ putStrLn "glTexSubImage2D" >> return ()

glTexSubImage3D :: MonadIO m => GLenum -> GLint -> GLint -> GLint -> GLint -> GLsizei -> GLsizei -> GLsizei -> GLenum -> GLenum -> Ptr () -> m ()
glTexSubImage3D _ _ _ _ _ _ _ _ _ _ _ = liftIO $ putStrLn "glTexSubImage3D" >> return ()

glGetTexImage :: MonadIO m => GLenum -> GLint -> GLenum -> GLenum -> Ptr () -> m ()
glGetTexImage _ _ _ _ _ = liftIO $ putStrLn "glGetTexImage" >> return ()

glGenerateMipmap :: MonadIO m => GLenum -> m ()
glGenerateMipmap _ = liftIO $ putStrLn "glGenerateMipmap" >> return ()

glTexParameterf :: MonadIO m => GLenum -> GLenum -> GLfloat -> m ()
glTexParameterf _ _ _ = liftIO $ putStrLn "glTexParameterf" >> return ()

glFramebufferTexture1D :: MonadIO m => GLenum -> GLenum -> GLenum -> GLuint -> GLint -> m ()
glFramebufferTexture1D _ _ _ _ _ = liftIO $ putStrLn "glFramebufferTexture1D" >> return ()

glFramebufferTextureLayer :: MonadIO m => GLenum -> GLenum -> GLuint -> GLint -> GLint -> m ()
glFramebufferTextureLayer _ _ _ _ _ = liftIO $ putStrLn "glFramebufferTextureLayer" >> return ()

glFramebufferTexture2D :: MonadIO m => GLenum -> GLenum -> GLenum -> GLuint -> GLint -> m ()
glFramebufferTexture2D _ _ _ _ _ = liftIO $ putStrLn "glFramebufferTexture2D" >> return ()

glFramebufferRenderbuffer :: MonadIO m => GLenum -> GLenum -> GLenum -> GLuint -> m ()
glFramebufferRenderbuffer _ _ _ _ = liftIO $ putStrLn "glFramebufferRenderbuffer" >> return ()

glScissor :: MonadIO m => GLint -> GLint -> GLsizei -> GLsizei -> m ()
glScissor _ _ _ _ = liftIO $ putStrLn "glScissor" >> return ()

glViewport :: MonadIO m => GLint -> GLint -> GLsizei -> GLsizei -> m ()
glViewport _ _ _ _ = liftIO $ putStrLn "glViewport" >> return ()

glDepthRange :: MonadIO m => GLdouble -> GLdouble -> m ()
glDepthRange _ _ = liftIO $ putStrLn "glDepthRange" >> return ()

glCullFace :: MonadIO m => GLenum -> m ()
glCullFace _ = liftIO $ putStrLn "glCullFace" >> return ()

glEnablei :: MonadIO m => GLenum -> GLuint -> m ()
glEnablei _ _ = liftIO $ putStrLn "glEnablei" >> return ()

glDisablei :: MonadIO m => GLenum -> GLuint -> m ()
glDisablei _ _ = liftIO $ putStrLn "glDisablei" >> return ()

glColorMaski :: MonadIO m => GLuint -> GLboolean -> GLboolean -> GLboolean -> GLboolean -> m ()
glColorMaski _ _ _ _ _ = liftIO $ putStrLn "glColorMaski" >> return ()

glBlendEquationSeparate :: MonadIO m => GLenum -> GLenum -> m ()
glBlendEquationSeparate _ _ = liftIO $ putStrLn "glBlendEquationSeparate" >> return ()

glBlendFuncSeparate :: MonadIO m => GLenum -> GLenum -> GLenum -> GLenum -> m ()
glBlendFuncSeparate _ _ _ _ = liftIO $ putStrLn "glBlendFuncSeparate" >> return ()

glBlendColor :: MonadIO m => GLfloat -> GLfloat -> GLfloat -> GLfloat -> m ()
glBlendColor _ _ _ _ = liftIO $ putStrLn "glBlendColor" >> return ()

glLogicOp :: MonadIO m => GLenum -> m ()
glLogicOp _ = liftIO $ putStrLn "glLogicOp" >> return ()

glDepthFunc :: MonadIO m => GLenum -> m ()
glDepthFunc _ = liftIO $ putStrLn "glDepthFunc" >> return ()

glDepthMask :: MonadIO m => GLboolean -> m ()
glDepthMask _ = liftIO $ putStrLn "glDepthMask" >> return ()

glStencilFuncSeparate :: MonadIO m => GLenum -> GLenum -> GLint -> GLuint -> m ()
glStencilFuncSeparate _ _ _ _ = liftIO $ putStrLn "glStencilFuncSeparate" >> return ()

glStencilOpSeparate :: MonadIO m => GLenum -> GLenum -> GLenum -> GLenum -> m ()
glStencilOpSeparate _ _ _ _ = liftIO $ putStrLn "glStencilOpSeparate" >> return ()

glStencilMaskSeparate :: MonadIO m => GLenum -> GLuint -> m ()
glStencilMaskSeparate _ _ = liftIO $ putStrLn "glStencilMaskSeparate" >> return ()

glColorMask :: MonadIO m => GLboolean -> GLboolean -> GLboolean -> GLboolean -> m ()
glColorMask _ _ _ _ = liftIO $ putStrLn "glColorMask" >> return ()

glStencilMask :: MonadIO m => GLuint -> m ()
glStencilMask _ = liftIO $ putStrLn "glStencilMask" >> return ()

glClearBufferfi :: MonadIO m => GLenum -> GLint -> GLfloat -> GLint -> m ()
glClearBufferfi _ _ _ _ = liftIO $ putStrLn "glClearBufferfi" >> return ()

-- Core 3.3

glVertexAttribDivisor :: MonadIO m => GLuint -> GLuint -> m ()
glVertexAttribDivisor _ _ = liftIO $ putStrLn "glVertexAttribDivisor" >> return ()
